{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "1.1.0-alpha.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-1.1.0-alpha.6.jar",
          "url": "amber-common-1.1.0-alpha.6.jar",
          "size": 79695,
          "sha512": "228d385e638531aa81f6180853174c2a5d67a80be206417db30e3062eed59c076d7bc04da2d96f18b4cdfdf6aa151669729d9060e397cb67135d20ca78dd818c",
          "sha256": "89a879004ff8fbe4c573dd9df89465817358a399e624aaab7b6e322df82ca48b",
          "sha1": "67a6bd5ac51ab6fe2a5d9a9d8e4b7605d596d735",
          "md5": "d219c23339cc09591a41a1123df69a67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-1.1.0-alpha.6.jar",
          "url": "amber-common-1.1.0-alpha.6.jar",
          "size": 79695,
          "sha512": "228d385e638531aa81f6180853174c2a5d67a80be206417db30e3062eed59c076d7bc04da2d96f18b4cdfdf6aa151669729d9060e397cb67135d20ca78dd818c",
          "sha256": "89a879004ff8fbe4c573dd9df89465817358a399e624aaab7b6e322df82ca48b",
          "sha1": "67a6bd5ac51ab6fe2a5d9a9d8e4b7605d596d735",
          "md5": "d219c23339cc09591a41a1123df69a67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-1.1.0-alpha.6-sources.jar",
          "url": "amber-common-1.1.0-alpha.6-sources.jar",
          "size": 68695,
          "sha512": "c0a031ae809d5507ebc51ac6f246f6d483c14a8e62e0f28b9e3501c40e117c005e9987fd9cc6e2cdd25e531d8ba59982ce8810fe0bded525bc438f731c8e4278",
          "sha256": "669bff26f818b8e69d8b4d8cc9c3a8fc98bdcf37f9ab2c610d13ed34651bb6dd",
          "sha1": "d48edd698365d5a4d413e4b235d5dc8985c0eec3",
          "md5": "da8af64c8b3b8708ec93224dc90440b4"
        }
      ]
    }
  ]
}
