{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "6.0.12+1.21.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-6.0.12+1.21.7.jar",
          "url": "amber-fabric-6.0.12+1.21.7.jar",
          "size": 192514,
          "sha512": "cd6043fe9d68c3b4482b240d23fdfe2007d0d4894ecca4b356871af5035fe8a92c5f8d1ed0c3aaef605a2e762f7bc79afb8e1d4bed5f86fb8330161f7a2c54d7",
          "sha256": "e32b5422194f664ab87151e5856f8dbb4366c8cc16295f374dcc93209d9eed19",
          "sha1": "95f215007a3d819b49e7e92b3d8ca5e25c561d8e",
          "md5": "133e2d7f1e10c605c5c27eb411a2bc2b"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.7",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "6.0.12+1.21.7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "15.0.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-6.0.12+1.21.7.jar",
          "url": "amber-fabric-6.0.12+1.21.7.jar",
          "size": 192514,
          "sha512": "cd6043fe9d68c3b4482b240d23fdfe2007d0d4894ecca4b356871af5035fe8a92c5f8d1ed0c3aaef605a2e762f7bc79afb8e1d4bed5f86fb8330161f7a2c54d7",
          "sha256": "e32b5422194f664ab87151e5856f8dbb4366c8cc16295f374dcc93209d9eed19",
          "sha1": "95f215007a3d819b49e7e92b3d8ca5e25c561d8e",
          "md5": "133e2d7f1e10c605c5c27eb411a2bc2b"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.7",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "6.0.12+1.21.7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-6.0.12+1.21.7-sources.jar",
          "url": "amber-fabric-6.0.12+1.21.7-sources.jar",
          "size": 143031,
          "sha512": "4bb1fb6b09342184ec8e30193d2391bdd9818bcff36007b572678af4826bb4854a4d9cca1b97e96a32119f9846f439e233ae99dc50b830812f6cd563ddcebfa8",
          "sha256": "4a6d01b8719bb210865f117b01f0de6172c2aa7b49b4179cb5f3edc25e257a33",
          "sha1": "e26a3eceee7b21c799d47eca4c46b4fe150b98c3",
          "md5": "13658413faed81225a0d11814d948471"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.7",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "6.0.12+1.21.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-6.0.12+1.21.7-javadoc.jar",
          "url": "amber-fabric-6.0.12+1.21.7-javadoc.jar",
          "size": 494546,
          "sha512": "666c79d13245f0cafa1d284f4ba31ef3dec182fd7537b4cca9f4ba6f90945bb438276f6f6ea35c7e6f4ed8a84574ea8959626f2a79b1faa2f4750a3cfa9ecc7a",
          "sha256": "b984fe1a13e49b78c7f36e9c9f183d5dd502fb958a61ba781841ec536470a3cd",
          "sha1": "c7576084e8193e97f20894fba6b8da5e236506ff",
          "md5": "c498db3279940d0112937c73b9b55945"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.7",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "6.0.12+1.21.7"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "6.0.12+1.21.7"
        }
      ]
    }
  ]
}
