{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "1.3.0-beta.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-neoforge-1.3.0-beta.2+1.21.1.jar",
          "size": 84783,
          "sha512": "1881637bdabb6391adb53aa9a8c424364f420585fba5899e0da2b15adb78c7b4dec23a0794419ddad243018aebd61d8756b56c506cd441dfbc04c18eca92f5f8",
          "sha256": "50430aec838b371c87312c1696d7d6c18aa96d88dd71de1a9e309cd47c680143",
          "sha1": "4574533fc36da18853214e159c938d7042f66482",
          "md5": "5543a8b3491ddd6990f5174b734413f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "amber-neoforge-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-neoforge-1.3.0-beta.2+1.21.1.jar",
          "size": 84783,
          "sha512": "1881637bdabb6391adb53aa9a8c424364f420585fba5899e0da2b15adb78c7b4dec23a0794419ddad243018aebd61d8756b56c506cd441dfbc04c18eca92f5f8",
          "sha256": "50430aec838b371c87312c1696d7d6c18aa96d88dd71de1a9e309cd47c680143",
          "sha1": "4574533fc36da18853214e159c938d7042f66482",
          "md5": "5543a8b3491ddd6990f5174b734413f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-1.3.0-beta.2+1.21.1-sources.jar",
          "url": "amber-neoforge-1.3.0-beta.2+1.21.1-sources.jar",
          "size": 53607,
          "sha512": "7bc262f8a008b3fa4ad28a2a4194054dacc4184f8eb3fd06c736360c24a9bfec31e396852893e297c10f25161c733a9fbda5f07ff72059df6b78700105874ca0",
          "sha256": "f40785be298afb13d18301f04b47b0ed353ecfa8daea453315e1a67e70b91522",
          "sha1": "139a2b638d43e73fd68e05d7d7a54763b0703372",
          "md5": "4530be790a6742f20601790a3d7cb2f9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "url": "amber-neoforge-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "size": 83392,
          "sha512": "5ca7a237dd7ff4155bfecd9f2f5e9896719f1d2ddec0d89d11341ded892fb51ba03bfc0cb0a73717de3056eb67033de9c544f48f2b93ad5c7ef14d5a2bf733e0",
          "sha256": "6096ee1ff4cd919687276032a0bf54cdff08999960d5f828be27175883b477ee",
          "sha1": "1f8a9fefadba8dbf654d87ad2620d123bb8fe8ac",
          "md5": "b51d9646d6dd696c42b8454ceb80c8dc"
        }
      ]
    }
  ]
}
