{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "1.3.0-beta.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.20.1.jar",
          "size": 81785,
          "sha512": "e7c0bc8dbe4e77d9335e64fe0eba9df8b89bb1fb2fb93c57a40dae67bc79daeebf260f25978a5f729eeda12b6601567b2d610fcadc584c58329d44fdbb847408",
          "sha256": "a81304225bd1299a74124c3038390fbff6741dda948123ca8316e9ed5ca82d37",
          "sha1": "c7e6f2eb98d5a3db897d80934f04baa932175e0d",
          "md5": "0793ba73aad0190360f7513e71268034"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.20.1.jar",
          "size": 81785,
          "sha512": "e7c0bc8dbe4e77d9335e64fe0eba9df8b89bb1fb2fb93c57a40dae67bc79daeebf260f25978a5f729eeda12b6601567b2d610fcadc584c58329d44fdbb847408",
          "sha256": "a81304225bd1299a74124c3038390fbff6741dda948123ca8316e9ed5ca82d37",
          "sha1": "c7e6f2eb98d5a3db897d80934f04baa932175e0d",
          "md5": "0793ba73aad0190360f7513e71268034"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.20.1-sources.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.20.1-sources.jar",
          "size": 54204,
          "sha512": "bf4ce9122b6e2720b0d7d11605e7348ba40a53cf752497fdd296bbc3231151efbc3237e4f83425a4427f8c86a18e3c4892925c4def88e6273a456ac77b1129bc",
          "sha256": "c4ef6d72c599b4406f46b17fb7661f6e3e87bc6f766f06faabe1f13b690f8afe",
          "sha1": "f8dc04efb160117a499289c043099517343a5667",
          "md5": "6b7d891442e4921243a5a810bbf5cc5e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.20.1-dev-shadow.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.20.1-dev-shadow.jar",
          "size": 80457,
          "sha512": "9d22e45591851f978c531d78dcedc55b9b7dca93f1599e6008bbf95c460d0851f82028e7156c6e0770e888e6521d248979e9e62843c77a230c0f18a027a834c1",
          "sha256": "2fd97cd4a47e4f2e8197357a6d8d7aae5f965f771e2189fd716cd1a3b1c1001e",
          "sha1": "a9ca8460520a33b51e8a77c94f956aa5a01e2df4",
          "md5": "14e0a4d16a5abd6c7a7ff00ccc9d340a"
        }
      ]
    }
  ]
}
