{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "1.2.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-1.2.0-beta.1.jar",
          "url": "amber-neoforge-1.2.0-beta.1.jar",
          "size": 81752,
          "sha512": "61f21115cd765ca5b85764a6e4814eb7e5bf9ee064a3bfe154c5672c812a6c1f5120e308e030e72f367a7b5173cb21d57686b3206dc0209b4956ec702930bc9d",
          "sha256": "98dc9e4a0df7c1c3c1030bbe2b5cecf53a1139cf25a52376ba9d81929466f19a",
          "sha1": "c5609b229360cb2e547f563140274156b5438921",
          "md5": "63e7bd822598c78e7e20dfb2d97fd354"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-neoforge-1.2.0-beta.1.jar",
          "url": "amber-neoforge-1.2.0-beta.1.jar",
          "size": 81752,
          "sha512": "61f21115cd765ca5b85764a6e4814eb7e5bf9ee064a3bfe154c5672c812a6c1f5120e308e030e72f367a7b5173cb21d57686b3206dc0209b4956ec702930bc9d",
          "sha256": "98dc9e4a0df7c1c3c1030bbe2b5cecf53a1139cf25a52376ba9d81929466f19a",
          "sha1": "c5609b229360cb2e547f563140274156b5438921",
          "md5": "63e7bd822598c78e7e20dfb2d97fd354"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-1.2.0-beta.1-sources.jar",
          "url": "amber-neoforge-1.2.0-beta.1-sources.jar",
          "size": 54627,
          "sha512": "3e71a8ce01035a67a3746398c646e80bfec997afd22efe9374de5db2103b0f6c14c46c87c5f31397d159c05740456f47ad027ee72be57764960d5530f27dcd9f",
          "sha256": "3299cfa905978c91238f9d94348c6d513c84391ca2c976aeb234ee5669303498",
          "sha1": "d9c7b838cb441704db2e4f539d4cfb5a176b9dd8",
          "md5": "ebc9e26982f66fb3aa123f1e46c50e23"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-1.2.0-beta.1-dev-shadow.jar",
          "url": "amber-neoforge-1.2.0-beta.1-dev-shadow.jar",
          "size": 80509,
          "sha512": "f7d69307dc080222a38f74c10f513338ebd59af5103860a7b1b1afcea738eaad706ece3aa0a007bcf15dc4987c5d23ebcb77c1450b08e29d6588095817c0a5c0",
          "sha256": "15c0075d54da5dc22c15910909d709feb39cffcd2cc7fe671ebf1cea8236c673",
          "sha1": "d7cfd33779d01f547817233bd657fef54e666856",
          "md5": "82db6255afd12a6ab875a1db8326ce9b"
        }
      ]
    }
  ]
}
