{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "4.0.0+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-4.0.0+1.21.5.jar",
          "url": "amber-neoforge-4.0.0+1.21.5.jar",
          "size": 113013,
          "sha512": "41a9ef1760d3ecd999d7dce765f6f94824de6c047184f9ee6bff0b5441203d7e9dc4ce7ff1f24852200715d19cbb6acc32dfa573346c81df522d5062519d1210",
          "sha256": "5745a7f879ff99b8e6696ba7ba9f3aa773ba975395bed1a3dc984398db3b9a09",
          "sha1": "d07b74d1c3aea91425fc64928a5f768702f38229",
          "md5": "a17f32e809d128437d5f496732d255f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-4.0.0+1.21.5.jar",
          "url": "amber-neoforge-4.0.0+1.21.5.jar",
          "size": 113013,
          "sha512": "41a9ef1760d3ecd999d7dce765f6f94824de6c047184f9ee6bff0b5441203d7e9dc4ce7ff1f24852200715d19cbb6acc32dfa573346c81df522d5062519d1210",
          "sha256": "5745a7f879ff99b8e6696ba7ba9f3aa773ba975395bed1a3dc984398db3b9a09",
          "sha1": "d07b74d1c3aea91425fc64928a5f768702f38229",
          "md5": "a17f32e809d128437d5f496732d255f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-4.0.0+1.21.5-sources.jar",
          "url": "amber-neoforge-4.0.0+1.21.5-sources.jar",
          "size": 57868,
          "sha512": "47b965ad76f5b497090b67bc665aa2b614357ec51bb73907fec6d194a6c64a8fbaaaaa0b2049a69b4146ba2617118174e1dd7a23d50cfb9203a27f096edac1dd",
          "sha256": "581f1a76fda573fd8de68eb83a65809457b032a9086080860d77d0558ee7549c",
          "sha1": "bffc2358fb93cc16ec02f2049a40e929e2445d81",
          "md5": "417fac0e4a878b2d3307521ad427a1f6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-4.0.0+1.21.5-dev-shadow.jar",
          "url": "amber-neoforge-4.0.0+1.21.5-dev-shadow.jar",
          "size": 110701,
          "sha512": "0997591de98d461bade6fdef51abb105125591687634a9a36f3f08296a65e0a2ca4c2db3ac84a0df559159a0c652c003fcc032613d3ea9aff53cc63fa72b9b4a",
          "sha256": "11519b83bba16e03424bdaf9266d514da4877a527e33ec534a25d6548c84766d",
          "sha1": "7a40b91af2957f8c772915369d6fe7b5bb2defd9",
          "md5": "2faf67b1a6d7361653fc0a5bd886b547"
        }
      ]
    }
  ]
}
