{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "1.3.0-beta.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-common-1.3.0-beta.2+1.20.1.jar",
          "size": 80611,
          "sha512": "d9e92042f5a99f1d6802603d3205c98c1289f0dd08b43959ee7b45615f966f480c4ed6dee3468ac5481fb5396a5df290b2bb61e3c70bffe226c1db1d8536585a",
          "sha256": "78030e1140f8b26a7e17272e3ad532b2fe8344c0c04359478582046eab075770",
          "sha1": "805788e77cda998f35b5bb4a1dd98a2dd0bf4f10",
          "md5": "01930b15cfc69fae4106c0b6d5879087"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-common-1.3.0-beta.2+1.20.1.jar",
          "size": 80611,
          "sha512": "d9e92042f5a99f1d6802603d3205c98c1289f0dd08b43959ee7b45615f966f480c4ed6dee3468ac5481fb5396a5df290b2bb61e3c70bffe226c1db1d8536585a",
          "sha256": "78030e1140f8b26a7e17272e3ad532b2fe8344c0c04359478582046eab075770",
          "sha1": "805788e77cda998f35b5bb4a1dd98a2dd0bf4f10",
          "md5": "01930b15cfc69fae4106c0b6d5879087"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-1.3.0-beta.2+1.20.1-sources.jar",
          "url": "amber-common-1.3.0-beta.2+1.20.1-sources.jar",
          "size": 68801,
          "sha512": "6e9a6bba73ee47ef4bf3a93a6df40e4717ae34c50a052d9a0f681e751761861a880000666742bcf244f51ad4882643352e2b359e77c1e46dfa9c583aa8f74858",
          "sha256": "5b06fdd88c9baf9c4697f6284098ae265c8b61933a2ab7d6dcc24c281b489b0a",
          "sha1": "f1463ed5dd823d54377cf00af99ad5c05083e9c4",
          "md5": "009270903aa33cdc599ec5950df1302f"
        }
      ]
    }
  ]
}
