{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "3.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.1.jar",
          "url": "amber-neoforge-3.0.0+1.21.1.jar",
          "size": 113380,
          "sha512": "82bc71206918a503d4212d1ce00dd606f6a2802969d2f9bb707814953f15ff8274064b97325b6857cd5e7ff53c7c071c42c5688891b50f1b3e2271c7dc074db3",
          "sha256": "1b2861e4209b57132776167d8b90dd9570dbe62d3a0afb6f60505c88215361bf",
          "sha1": "efe2bcc877543b2d75d0318d93e974dbb1aa8680",
          "md5": "071a96a6c01883381759a912c7facdd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.1.jar",
          "url": "amber-neoforge-3.0.0+1.21.1.jar",
          "size": 113380,
          "sha512": "82bc71206918a503d4212d1ce00dd606f6a2802969d2f9bb707814953f15ff8274064b97325b6857cd5e7ff53c7c071c42c5688891b50f1b3e2271c7dc074db3",
          "sha256": "1b2861e4209b57132776167d8b90dd9570dbe62d3a0afb6f60505c88215361bf",
          "sha1": "efe2bcc877543b2d75d0318d93e974dbb1aa8680",
          "md5": "071a96a6c01883381759a912c7facdd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.1-sources.jar",
          "url": "amber-neoforge-3.0.0+1.21.1-sources.jar",
          "size": 57877,
          "sha512": "c1d58dce9350e0256a95e081414ea7aa3fd368a9e9466cc5946c02e4cab470e7f21bb340460a0a37ae3e1b16221ba5e362bed6ec8dc20e68fbefde953061e8c7",
          "sha256": "3b1128bf22897bf9ce510b6644d3981cd8b84a65ec1c565a926a7861c748634f",
          "sha1": "c630f172eb8375cead5ff764f77501141042f6fb",
          "md5": "f21a2f2746fc7d3f648b31a9c37ee2a9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.1-dev-shadow.jar",
          "url": "amber-neoforge-3.0.0+1.21.1-dev-shadow.jar",
          "size": 111071,
          "sha512": "1f1aa0c97c1f246161e9d66f6cf2d486c8a8d16282a196ca2587323e4a00e07297e013b26e462b901ebac0f62a3d937cbf593ad7b09550b9c7b7be021e86cecc",
          "sha256": "4969a7bae59dee2190da1b77edb81191b059430f0fd07cc5428ee6a50b5a4c59",
          "sha1": "c242667b35ebf7dfa48e44e53816af3c93b22aa1",
          "md5": "e3e8d94cd8fae1a457346b3a0971784c"
        }
      ]
    }
  ]
}
