{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "3.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.1.jar",
          "url": "amber-common-3.0.0+1.21.1.jar",
          "size": 108173,
          "sha512": "27a252db5b04095c18cfa0b41e6c2dd8b047ca39d620c7640bc91dec2d6e600208b4df05dc8864d88e351044d5dbf8d0f4092e927d4aa2b01a4de6f70d1ab40b",
          "sha256": "f71170f34fb5e29b3ab06cafe5da541d1a79836035594b367ad3153e1532790b",
          "sha1": "c9759eeaa0f3f399e3c8994d2f15af267c262819",
          "md5": "0c1091b988a4ee5570ed1b66d6185426"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.1.jar",
          "url": "amber-common-3.0.0+1.21.1.jar",
          "size": 108173,
          "sha512": "27a252db5b04095c18cfa0b41e6c2dd8b047ca39d620c7640bc91dec2d6e600208b4df05dc8864d88e351044d5dbf8d0f4092e927d4aa2b01a4de6f70d1ab40b",
          "sha256": "f71170f34fb5e29b3ab06cafe5da541d1a79836035594b367ad3153e1532790b",
          "sha1": "c9759eeaa0f3f399e3c8994d2f15af267c262819",
          "md5": "0c1091b988a4ee5570ed1b66d6185426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.1-sources.jar",
          "url": "amber-common-3.0.0+1.21.1-sources.jar",
          "size": 87011,
          "sha512": "f6c3c38ca8c3a20e4903b9c61a6b1a9af8347cd4f805c4c4bf46f5fcee76fc3cf51203dc2f38c24720a29aabab37c175ee41b3b4903dde332e367e43f589e62b",
          "sha256": "5e88d656c4116dca2fb8ce3d2bbcfa2427c67c6977e481902cc783771b18509d",
          "sha1": "c45025546cb0b6f65a9b49b3fa925f86072ea040",
          "md5": "6ad4f687637c9326ae35b0ab5e4340e5"
        }
      ]
    }
  ]
}
