{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "2.0.0-beta.4+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "size": 83941,
          "sha512": "e67c433cbe6ba1d1835eedb0d3a95225da3bb96448f72e4838705e2e33cebe1803ec8afcc4d5a200018425b73d74a63f3387cc1ec0792434fe02d7016681d46d",
          "sha256": "dcefd00ecd0ed2441b9b82993b27f59b522e3e73ddcb0b5611dc621920d0ba20",
          "sha1": "1f5d8d3dee08661a32f9e944dd34644e28827bf0",
          "md5": "34b8ca817cc00ce7f71faced88c4e35f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "size": 83941,
          "sha512": "e67c433cbe6ba1d1835eedb0d3a95225da3bb96448f72e4838705e2e33cebe1803ec8afcc4d5a200018425b73d74a63f3387cc1ec0792434fe02d7016681d46d",
          "sha256": "dcefd00ecd0ed2441b9b82993b27f59b522e3e73ddcb0b5611dc621920d0ba20",
          "sha1": "1f5d8d3dee08661a32f9e944dd34644e28827bf0",
          "md5": "34b8ca817cc00ce7f71faced88c4e35f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4-sources.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4-sources.jar",
          "size": 53603,
          "sha512": "664201f682b39e9adc1dd612d9de8ed3898102fc7688c8658eadbed025c78d66c36063dbfcddd3397576a6233646ee8769c9106b3f0b41a307169930a97bc049",
          "sha256": "9fcdd09f4818201462ee349f174c6a354ed681a30258f9323441f9f7c7c478b5",
          "sha1": "7a4978bd60b42c8cac02c27c1c059f4365523307",
          "md5": "0da0fc1ba80a17447c6beb3d5b04960c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "size": 82579,
          "sha512": "656b16b8923119cc701ccd60ef18cac1d403beb161d7b785a0efe8f664e0034987686eb9d15f7acea02ec7aa4ab3b2014cc224cdfbeeb53d75973022e944d8be",
          "sha256": "1052076ef6c4fbd3971d1901f8e4a1f19ddd9165daa157ba5d79b913c6f048ba",
          "sha1": "f77efa703dad3ff6ab07f363cbf97a5350c436b7",
          "md5": "ce9aa364b2203b0d727d241479aa0952"
        }
      ]
    }
  ]
}
