{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "2.0.0-beta.4+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "size": 84018,
          "sha512": "cfd351ada73c9603449a9354f069862166ec121240227ab589e7955ac537d8cee64f3bea5fc4fe91983cee2220c19ebe46a3ff2b680e694df5c7a91e59be8866",
          "sha256": "77894be9c7ae97edcc42888cd5444662daf0d7a70bb3899b6fbb210f0b2e49f9",
          "sha1": "a9a85f9952d8f7df76e1d459f79f4ef40c4de81d",
          "md5": "6477e09d785c9efcb8b71bd8965fb5ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4.jar",
          "size": 84018,
          "sha512": "cfd351ada73c9603449a9354f069862166ec121240227ab589e7955ac537d8cee64f3bea5fc4fe91983cee2220c19ebe46a3ff2b680e694df5c7a91e59be8866",
          "sha256": "77894be9c7ae97edcc42888cd5444662daf0d7a70bb3899b6fbb210f0b2e49f9",
          "sha1": "a9a85f9952d8f7df76e1d459f79f4ef40c4de81d",
          "md5": "6477e09d785c9efcb8b71bd8965fb5ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4-sources.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4-sources.jar",
          "size": 53603,
          "sha512": "961e2b95739e4e572f93e19c9d7fe633659119353e2727f55df6a43b0ef78b4c84a3646bd75221fdff105fda78d51e370151f2f2119a59ed58a1c7b07efdb761",
          "sha256": "16bcfdc073f79ac2d28b8cbd23825f5b82142d57645e7ae02a5b5004916e4425",
          "sha1": "99f2aa79613cf46d772fccd51322cfe6ecafb2db",
          "md5": "600131ebc77c00d8496422849860f0f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "url": "amber-neoforge-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "size": 82655,
          "sha512": "18b2b235568429d3d24aa921e35ac8c6676acb7ce8ec71b740cf9edb572fbb91d283d0604c6041bd9fc270cfc781121bcb9a080e993f32bccad2bc46304a0706",
          "sha256": "a02d7148ecc349ece7b16244dc9d0f57fee0fe3e7f5aebd66f0449eb544e5424",
          "sha1": "721c5dbf5594b8946ca7cfb31dc889c7c3730eb9",
          "md5": "cad1f8dbb533ab83f689c1839c668d01"
        }
      ]
    }
  ]
}
