{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10.jar",
          "url": "amber-common-8.3.0+1.21.10.jar",
          "size": 232085,
          "sha512": "89554bfeec29309bd6586b850345f97ea70350b709aabf460cbf62a15185a2f15a2a1c48f30a18dec6e4b3523e8ba1cf13f0ba62b358099e2ab006aeba20ce5a",
          "sha256": "bc46d638ffbf467f49e41d437f427485c0a896779473f8fff0ee4ac10ded38f5",
          "sha1": "932e452d98569dc0e14605f2666e286e3b3d54d8",
          "md5": "6e3a7c3f7832a598bc24d3e1e017e208"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10.jar",
          "url": "amber-common-8.3.0+1.21.10.jar",
          "size": 232085,
          "sha512": "89554bfeec29309bd6586b850345f97ea70350b709aabf460cbf62a15185a2f15a2a1c48f30a18dec6e4b3523e8ba1cf13f0ba62b358099e2ab006aeba20ce5a",
          "sha256": "bc46d638ffbf467f49e41d437f427485c0a896779473f8fff0ee4ac10ded38f5",
          "sha1": "932e452d98569dc0e14605f2666e286e3b3d54d8",
          "md5": "6e3a7c3f7832a598bc24d3e1e017e208"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10-sources.jar",
          "url": "amber-common-8.3.0+1.21.10-sources.jar",
          "size": 156380,
          "sha512": "131ebb8d595816d9ca89968e0048be3bddb355082e0802d1af2e542cd2bdf52fb9a1de934cd613c630a69ff0982c41fd69f0d4fcc2178258fe7d45a850572cf2",
          "sha256": "66dccac3b07de55c68f3c16cb2b8e9918a21150bfc9e108f159f12bed1d44640",
          "sha1": "ae5404ccc0006a0bd9b53fa05b720be238f0fbe6",
          "md5": "8197dbd11da1848d98f6f55cdd398ee8"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-common-8.3.0+1.21.10-javadoc.jar",
          "size": 625010,
          "sha512": "351b7e583bff2ac698fec90d16bb47edb3d9be40adc4a0127e991ef38b11af3c8afb916b68ad8e0e36e54c4d1fc1714415c4a622a33f5a2b6a1b0f3e6e46cd85",
          "sha256": "f9c0c38f7bdda72cc5cd8ba185349b90b82df0059ddc5fc271e685b91b387dfb",
          "sha1": "461f884a7b64a9c1f1f82cece7d9785fdf97d220",
          "md5": "ada80505d9c72f5cc724af6ee053c45d"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
