{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10.jar",
          "url": "amber-common-8.3.0+1.21.10.jar",
          "size": 233425,
          "sha512": "576d9118481992d22d9c57180edc08ee2f8316a6734f9819bc1b5f7d261c824a15ac609d52902ac8d6298fc49239d5e3bc5b2c14e96d7479f22d52e110167d1b",
          "sha256": "e7fe3a96d9a3e7a725897b081fae544883ed92c8a7d36e4c5d3e083f105c56d1",
          "sha1": "4d4d73539d0efad23a5abaf35f73f01fac9f17e8",
          "md5": "d2402fd2788fabc2f9b1eb8a9c20b93c"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10.jar",
          "url": "amber-common-8.3.0+1.21.10.jar",
          "size": 233425,
          "sha512": "576d9118481992d22d9c57180edc08ee2f8316a6734f9819bc1b5f7d261c824a15ac609d52902ac8d6298fc49239d5e3bc5b2c14e96d7479f22d52e110167d1b",
          "sha256": "e7fe3a96d9a3e7a725897b081fae544883ed92c8a7d36e4c5d3e083f105c56d1",
          "sha1": "4d4d73539d0efad23a5abaf35f73f01fac9f17e8",
          "md5": "d2402fd2788fabc2f9b1eb8a9c20b93c"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10-sources.jar",
          "url": "amber-common-8.3.0+1.21.10-sources.jar",
          "size": 157580,
          "sha512": "85bda86acef31d061947f22cbb98126f3572d515a03a84206e5f5f067fd72f13259f134c59b95a031eaa5a5ac53c87923f655b92cf627435d8c290f32319ebd5",
          "sha256": "df243c5ff87e397128afe10e18a061a7d0af57d9b7cfcc14471896259b6691c0",
          "sha1": "6a4f42077ca0875cfe2da34d3dc14a3c6d5997bc",
          "md5": "f2bba62849769fa0f6d28c0d04ee3214"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-common-8.3.0+1.21.10-javadoc.jar",
          "size": 627148,
          "sha512": "3855b8bc7ea8b7e2942ab480042dcab779dfad4637265f3e198d8fff0ff1ccc3cfd328c551b90692e46cad93393da0b7f2b0b792a0c45906557531d33ca2b9b5",
          "sha256": "1327da800142a686f84bb9f4a52fa29b28a1a09dfd51bc250ebbf8dbe3ff6cc7",
          "sha1": "b9c00333d2fabdc0160fa3e8a22a8562fed5b7fb",
          "md5": "7f4292bf000f7ff9ff82b28ec491202c"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
