{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-quilt",
    "version": "1.3.0-beta.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-quilt-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-quilt-1.3.0-beta.2+1.21.1.jar",
          "size": 85175,
          "sha512": "064a126125e4d17e6ad2fe1d05840a6142a1034b6e5a3b937ac411d9c71dacace61fb69b4a4ed01abd6a0c341eeada649b7863d4117be05ed4ef2893f1cc4937",
          "sha256": "d7f173b90d4b1500e759131a6dbef088d663e6dd00d5cda100de45183633f058",
          "sha1": "70958c5476d28b80e255057591208f3c111480e4",
          "md5": "62152e050c174dcc0170bc06aa9567bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.quiltmc",
          "module": "quilt-loader",
          "version": {
            "requires": "0.27.1-beta.1"
          }
        },
        {
          "group": "org.quiltmc.quilted-fabric-api",
          "module": "quilted-fabric-api",
          "version": {
            "requires": "11.0.0-alpha.3+0.102.0-1.21"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "amber-quilt-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-quilt-1.3.0-beta.2+1.21.1.jar",
          "size": 85175,
          "sha512": "064a126125e4d17e6ad2fe1d05840a6142a1034b6e5a3b937ac411d9c71dacace61fb69b4a4ed01abd6a0c341eeada649b7863d4117be05ed4ef2893f1cc4937",
          "sha256": "d7f173b90d4b1500e759131a6dbef088d663e6dd00d5cda100de45183633f058",
          "sha1": "70958c5476d28b80e255057591208f3c111480e4",
          "md5": "62152e050c174dcc0170bc06aa9567bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-quilt-1.3.0-beta.2+1.21.1-sources.jar",
          "url": "amber-quilt-1.3.0-beta.2+1.21.1-sources.jar",
          "size": 3245,
          "sha512": "4a4f588153c9300527cbe05ad8e8c9e0b62f2d514be4df92ee3365fa6f4643eb2021145458d98bd3b7818305718714689c2c482fb5e042de70c826009ea72eb6",
          "sha256": "06a5f5757b53c80d2658a99826903ffd6b6ae4cf889821f3d8fccff86b1c9cb6",
          "sha1": "d08f6357bad8b87cc921d834cfd2a8cb10556987",
          "md5": "8819b715444d10edd2aca7defb4b53b8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-quilt-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "url": "amber-quilt-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "size": 83924,
          "sha512": "1399e12c5db42897b69fefb8e994c2a1d96a8d79e70ad9d5c04cb8d7ca39e2c2731086d6b97458b8e3b59c2ecd7e1773cb340de6318730d912a3d91d028321a2",
          "sha256": "4cc9d89e528b189fe852528a37bc5e6ca917b77410633f8bc470f35bda4cd43b",
          "sha1": "77d6bc333048e940bd4566d7cdf40868715ace36",
          "md5": "cc94997749a9b0af70ddffcd2059b272"
        }
      ]
    }
  ]
}
