{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 275538,
          "sha512": "85abcfbcf160cf3eee673bfab8adece90133a0f944a932c57d41fe6bc2bcb92bace6876660639b9730e0f2201b6cfd6b720c785691f474929bc209dd6ee9be7c",
          "sha256": "682ff5fe437139dc73a7a9afc1aac7d7f62ee9ed02d9a200a2db84e6e8a0c3e3",
          "sha1": "232faadb8a8513864f6ae9a43fddab4766851ac3",
          "md5": "9c582b8aa40e8486f9ad8e2cbc5b9f65"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 275538,
          "sha512": "85abcfbcf160cf3eee673bfab8adece90133a0f944a932c57d41fe6bc2bcb92bace6876660639b9730e0f2201b6cfd6b720c785691f474929bc209dd6ee9be7c",
          "sha256": "682ff5fe437139dc73a7a9afc1aac7d7f62ee9ed02d9a200a2db84e6e8a0c3e3",
          "sha1": "232faadb8a8513864f6ae9a43fddab4766851ac3",
          "md5": "9c582b8aa40e8486f9ad8e2cbc5b9f65"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "size": 174791,
          "sha512": "c39b1207928761a6cb6eff8765424fa6599f713e2d6784738b090242d20d72e490654ee321a4d055124fbc08d2caa5240df59ba316faa70a23a0c10cf85e5edc",
          "sha256": "d44a8ccd8e9e55332abf012644d6e0d48a709e57ff917608e3f382e9f5fcebe1",
          "sha1": "b771bb35b54034c0a77bfbc43954f74260330ea1",
          "md5": "834e2b6b5d9fbc043063c7b7c135c9d3"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "size": 693126,
          "sha512": "7ce46487d5047387e9dc66fd5430ff65956b6fca26b41f7cd2578ecf4f2dba47f52b575f3b6b0ec7a5ea1c88a2b1140d87a4445482cdcbd00af0b6daef1e3e23",
          "sha256": "8871f5ca4488254601b90d8a5f79943ec5b864b2ff23b921d55610acef68ddce",
          "sha1": "eb443afd9e874dcdda7e7d408b3aeccc1ee97009",
          "md5": "390a86e15c58771e0856d08982a69d30"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
