{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 244291,
          "sha512": "4c1bc06f78223d06e3b3476473bfe797a5063165d2fae0938c2f2e20873fa7a28178c75ff8848a579e23473de7b4ca278645b3e1697b4f8d6ca0349ec09e34f7",
          "sha256": "360edc6a863ca28b59f6cd179d03eec3f7da63734651d699bd3c11fb769472d4",
          "sha1": "09169afb1ec6ee0a4f25fa140a12128b9b436c2d",
          "md5": "85d83e33799b86c0743efc4ded7dc7f4"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 244291,
          "sha512": "4c1bc06f78223d06e3b3476473bfe797a5063165d2fae0938c2f2e20873fa7a28178c75ff8848a579e23473de7b4ca278645b3e1697b4f8d6ca0349ec09e34f7",
          "sha256": "360edc6a863ca28b59f6cd179d03eec3f7da63734651d699bd3c11fb769472d4",
          "sha1": "09169afb1ec6ee0a4f25fa140a12128b9b436c2d",
          "md5": "85d83e33799b86c0743efc4ded7dc7f4"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "size": 155037,
          "sha512": "278c1caae81abd590b3139fbc2afe52b006ce0755b34511ff9212d986474bd02507f60d0cc7c6d1627e72918d73aed827177b146bfd0ebc0331320b2cefdba26",
          "sha256": "487ca82feaf37a214c3edc366a6ec9c4b9d1c2eb775f1d80483cf8716ae3093f",
          "sha1": "cf17edc4b4736a29deac47436ff5735265daddb8",
          "md5": "07e188f752995144707e12b5cfacdf3a"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "size": 628143,
          "sha512": "5998eae5e5e148f89733e5bfb4cd08e6d0e4eface7cadf9f81a832ea3f2eb2bf0233c60764324358484e2384ad1dae034bf403fe73173eb0b4a1271ee69bc07e",
          "sha256": "e1f9e44c4f3116a3378392d572adc9372eabd64b9e009bf26cf235b113fe6dc2",
          "sha1": "ba75da254e6180cca3e728ed5abd31d74ddbecd3",
          "md5": "4bddbbd06226766957ed26fc561abb28"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
