{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 276878,
          "sha512": "359133b88b02fd44f86c46f3710ba03c9b4018962b273dc1c938f6be85f9484f818a1e5ff4a142ba495a442a4df475fd55a74f799b1777fce655e5d937db0993",
          "sha256": "ab139632e3e421a49d978d71ad5ff0e9df03eb4641a5432855a3b7b88ff1a68f",
          "sha1": "82395515c84907127de4975e3ca8f71592625aaf",
          "md5": "3dcff11b5e533916218db86f3d2ce20b"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10.jar",
          "url": "amber-neoforge-8.3.0+1.21.10.jar",
          "size": 276878,
          "sha512": "359133b88b02fd44f86c46f3710ba03c9b4018962b273dc1c938f6be85f9484f818a1e5ff4a142ba495a442a4df475fd55a74f799b1777fce655e5d937db0993",
          "sha256": "ab139632e3e421a49d978d71ad5ff0e9df03eb4641a5432855a3b7b88ff1a68f",
          "sha1": "82395515c84907127de4975e3ca8f71592625aaf",
          "md5": "3dcff11b5e533916218db86f3d2ce20b"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-sources.jar",
          "size": 175991,
          "sha512": "90edd9138e982c13fd0ac5137d448f160c5b288b3750ed123297b605bc7a44c8c7f3be007df89fea13352822507ca3ddc93ddf1037770839941c35e55f91c99b",
          "sha256": "a5f62db37f62e11ecb6f1c69b1748a9a586334af242cc4259a9171c8e5ecaf1d",
          "sha1": "3a85d87868d75871292bfd29c21991115fb91c2d",
          "md5": "7f7746992254a2978cd34eabeb647adc"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-neoforge-8.3.0+1.21.10-javadoc.jar",
          "size": 695242,
          "sha512": "0d017c041eb61387d749bd1f456b900978ab81859d82894dbe4886a28ce0e21dba83cd29f1be54b93f15e27b3460471f1c7a0b3ead784e4b1633fdfcffb36dbd",
          "sha256": "3daaa1c1641677dcc814678e5136c0c666e97a14b740abeb7e86ac6a3e01a283",
          "sha1": "d3909f35446c60b131b962db08ac6afb3c055b51",
          "md5": "2581944f8d7477ef711eeadf5d507b18"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.10",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
