{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "2.0.0-beta.4+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-common-2.0.0-beta.4+1.21.4.jar",
          "size": 83302,
          "sha512": "962e15312599c5b7b52a2d1ae1a2e682f04e841ee9c8897249efa7a5d13bb3bf5d291a6327380531e294d62cc025d1a3b430f5869e3a315ee3b6488af9058ad0",
          "sha256": "528d7decade8b51593557a39ac7ba4d8956f9fc326a48558da69a2bbd4381c64",
          "sha1": "8b2c83de6859fcbe671a2ff7a98297bb81edddb0",
          "md5": "ba27c6c423c247728da8caf7f47fa546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-common-2.0.0-beta.4+1.21.4.jar",
          "size": 83302,
          "sha512": "962e15312599c5b7b52a2d1ae1a2e682f04e841ee9c8897249efa7a5d13bb3bf5d291a6327380531e294d62cc025d1a3b430f5869e3a315ee3b6488af9058ad0",
          "sha256": "528d7decade8b51593557a39ac7ba4d8956f9fc326a48558da69a2bbd4381c64",
          "sha1": "8b2c83de6859fcbe671a2ff7a98297bb81edddb0",
          "md5": "ba27c6c423c247728da8caf7f47fa546"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-2.0.0-beta.4+1.21.4-sources.jar",
          "url": "amber-common-2.0.0-beta.4+1.21.4-sources.jar",
          "size": 70136,
          "sha512": "720b09292c18e3a607bed148732f02bb289810dba67a58ae418750ab384a621efa2958012c95229dccb68eab4ff9d91b5747bbdd332911bc88e77e304f57a73d",
          "sha256": "df45a2043ad7403a2ca96b1ab57302b56928ae7fe60b359eb201570693d46799",
          "sha1": "164d0d4043294fde30ea8dce834b69ed6272aa6b",
          "md5": "637694e5fd3eeaa738b4b10e0303c62a"
        }
      ]
    }
  ]
}
