/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ModrinthClient } from './ModrinthClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AlgorithmIdentifier } from './models/AlgorithmIdentifier';
export type { AuthError } from './models/AuthError';
export type { BaseProject } from './models/BaseProject';
export type { BaseVersion } from './models/BaseVersion';
export type { CategoryTag } from './models/CategoryTag';
export type { CreatableProject } from './models/CreatableProject';
export type { CreatableProjectGalleryItem } from './models/CreatableProjectGalleryItem';
export type { CreatableReport } from './models/CreatableReport';
export type { CreatableVersion } from './models/CreatableVersion';
export type { CreateProjectBody } from './models/CreateProjectBody';
export type { CreateVersionBody } from './models/CreateVersionBody';
export type { DonationPlatformTag } from './models/DonationPlatformTag';
export type { EditableFileType } from './models/EditableFileType';
export type { EditableProject } from './models/EditableProject';
export type { EditableUser } from './models/EditableUser';
export type { EditableVersion } from './models/EditableVersion';
export type { FileHashIdentifier } from './models/FileHashIdentifier';
export type { ForgeUpdateCheckerPromos } from './models/ForgeUpdateCheckerPromos';
export type { ForgeUpdates } from './models/ForgeUpdates';
export type { GalleryImage } from './models/GalleryImage';
export type { GameVersionTag } from './models/GameVersionTag';
export type { GetLatestVersionFromHashBody } from './models/GetLatestVersionFromHashBody';
export type { GetLatestVersionsFromHashesBody } from './models/GetLatestVersionsFromHashesBody';
export type { HashList } from './models/HashList';
export type { HashVersionMap } from './models/HashVersionMap';
export type { InvalidInputError } from './models/InvalidInputError';
export type { License } from './models/License';
export type { LicenseTag } from './models/LicenseTag';
export type { LoaderTag } from './models/LoaderTag';
export type { ModeratorMessage } from './models/ModeratorMessage';
export type { ModifiableProject } from './models/ModifiableProject';
export type { ModifyTeamMemberBody } from './models/ModifyTeamMemberBody';
export type { MultipleHashQueryIdentifier } from './models/MultipleHashQueryIdentifier';
export type { MultipleProjectIdentifier } from './models/MultipleProjectIdentifier';
export type { NonSearchProject } from './models/NonSearchProject';
export type { Notification } from './models/Notification';
export type { NotificationAction } from './models/NotificationAction';
export type { NotificationIdentifier } from './models/NotificationIdentifier';
export type { PatchProjectsBody } from './models/PatchProjectsBody';
export type { Project } from './models/Project';
export type { ProjectDependencyList } from './models/ProjectDependencyList';
export type { ProjectDonationURL } from './models/ProjectDonationURL';
export type { ProjectIdentifier } from './models/ProjectIdentifier';
export type { ProjectIdentifier } from './models/ProjectIdentifier';
export type { ProjectLicense } from './models/ProjectLicense';
export type { ProjectResult } from './models/ProjectResult';
export type { Report } from './models/Report';
export type { ReportIdentifier } from './models/ReportIdentifier';
export type { Schedule } from './models/Schedule';
export type { SearchResults } from './models/SearchResults';
export type { ServerRenderedProject } from './models/ServerRenderedProject';
export type { Statistics } from './models/Statistics';
export type { TeamIdentifier } from './models/TeamIdentifier';
export type { TeamMember } from './models/TeamMember';
export type { Thread } from './models/Thread';
export type { ThreadIdentifier } from './models/ThreadIdentifier';
export type { ThreadMessage } from './models/ThreadMessage';
export type { ThreadMessageBody } from './models/ThreadMessageBody';
export type { User } from './models/User';
export type { UserIdentifier } from './models/UserIdentifier';
export type { UserIdentifier } from './models/UserIdentifier';
export type { UserPayoutData } from './models/UserPayoutData';
export type { UserPayoutHistory } from './models/UserPayoutHistory';
export type { UserPayoutHistoryEntry } from './models/UserPayoutHistoryEntry';
export type { Version } from './models/Version';
export type { VersionDependency } from './models/VersionDependency';
export type { VersionFile } from './models/VersionFile';
export type { VersionFileHashes } from './models/VersionFileHashes';
export type { VersionIdentifier } from './models/VersionIdentifier';

export { MiscService } from './services/MiscService';
export { NotificationsService } from './services/NotificationsService';
export { ProjectsService } from './services/ProjectsService';
export { TagsService } from './services/TagsService';
export { TeamsService } from './services/TeamsService';
export { ThreadsService } from './services/ThreadsService';
export { UsersService } from './services/UsersService';
export { VersionFilesService } from './services/VersionFilesService';
export { VersionsService } from './services/VersionsService';
