{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "6.0.5+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-6.0.5+1.21.6.jar",
          "url": "amber-neoforge-6.0.5+1.21.6.jar",
          "size": 148579,
          "sha512": "9353d15774d5c84632f5408d02a8f6d3cfa6952dd370b0cb044627f22a4cf32d19d4deb74abe2d1f4d8a5fe119f55b375da098a38265e428c4b178841a5a843d",
          "sha256": "d59465ec070a7cc524c642ecb28877bd36c1e60b0a45a08cb68960c88c65f594",
          "sha1": "5fe7b95b9a82c36462ea3075a91f2b1f4f206a23",
          "md5": "8af5e73872baca6ff8379023a5b93d98"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.6",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.5+1.21.6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-6.0.5+1.21.6.jar",
          "url": "amber-neoforge-6.0.5+1.21.6.jar",
          "size": 148579,
          "sha512": "9353d15774d5c84632f5408d02a8f6d3cfa6952dd370b0cb044627f22a4cf32d19d4deb74abe2d1f4d8a5fe119f55b375da098a38265e428c4b178841a5a843d",
          "sha256": "d59465ec070a7cc524c642ecb28877bd36c1e60b0a45a08cb68960c88c65f594",
          "sha1": "5fe7b95b9a82c36462ea3075a91f2b1f4f206a23",
          "md5": "8af5e73872baca6ff8379023a5b93d98"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.6",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.5+1.21.6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-6.0.5+1.21.6-sources.jar",
          "url": "amber-neoforge-6.0.5+1.21.6-sources.jar",
          "size": 105811,
          "sha512": "17b5002cac319c94251ffb19c87d5875d743418dfa90122c5928ee5add7a74bb115bae54c3163590dc9e10da22a941026f38f3c655706caa959fc091229f27a9",
          "sha256": "5d74f3218611e73c6365c4fa0d6a232ddb25456fba74745db815b37e87e27797",
          "sha1": "9c9339a9b7ae393ba52f9ec98cc96a570d08e05d",
          "md5": "3c55b66d8719a2a02f73072f80cd8085"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.6",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.5+1.21.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-6.0.5+1.21.6-javadoc.jar",
          "url": "amber-neoforge-6.0.5+1.21.6-javadoc.jar",
          "size": 375657,
          "sha512": "2e5f17ad1ccfad199b3a412c8a2b2d89f59bb4c451a10c69b1177d17f84f7099786c74d22af2108636eb2e544b563f79041da01014cf19efecc16bcd6b38754d",
          "sha256": "dad3efa9d468d4cdc7f3467a254b3b2eac1935fa66a2046a10d66c6e76df2824",
          "sha1": "ff7f53dd33a52fdc6e6977c42078b38bba691746",
          "md5": "d4c48b7c8803379529a320c0e798dcb1"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.6",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "6.0.5+1.21.6"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "6.0.5+1.21.6"
        }
      ]
    }
  ]
}
