{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.mochila",
    "module": "mochila-common",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mochila-common-1.2.0.jar",
          "url": "mochila-common-1.2.0.jar",
          "size": 147844,
          "sha512": "9b3a34221c5b93843c49a3f66b4587bceb87a72ef71211a99a24ceb28b4be5271fab10471068c671fa1107a70db5c4b4c0f83d4093281ad2317dbe35d7354d01",
          "sha256": "b1dfcce710edcb4abec91db08a03fca49bf89cd5496107f8d4b66b046c7b088c",
          "sha1": "814a9496d0f2fc47d09b555f340749664922fa8e",
          "md5": "945b631753dc762bac12038746b6a233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "13.0.6"
          }
        },
        {
          "group": "com.iamkaf.amber",
          "module": "amber-common",
          "version": {
            "requires": "1.0.0-alpha.7"
          }
        }
      ],
      "files": [
        {
          "name": "mochila-common-1.2.0.jar",
          "url": "mochila-common-1.2.0.jar",
          "size": 147844,
          "sha512": "9b3a34221c5b93843c49a3f66b4587bceb87a72ef71211a99a24ceb28b4be5271fab10471068c671fa1107a70db5c4b4c0f83d4093281ad2317dbe35d7354d01",
          "sha256": "b1dfcce710edcb4abec91db08a03fca49bf89cd5496107f8d4b66b046c7b088c",
          "sha1": "814a9496d0f2fc47d09b555f340749664922fa8e",
          "md5": "945b631753dc762bac12038746b6a233"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mochila-common-1.2.0-sources.jar",
          "url": "mochila-common-1.2.0-sources.jar",
          "size": 128056,
          "sha512": "4cca967abdb094b8452d98e4ecf0bde9c1937e42ac3f6eb0c632e5dd96e4b65ec9c6b58ae98d31af125349711470ad484bb9f3866c465934202545588ba6d9d2",
          "sha256": "e6c85cc0afc53a8e4e603ae2f20da81cfbb087b72ac5c01f1fa36531000314ed",
          "sha1": "baeab1dacabfd5b92a31c8358857fbacf06cdf82",
          "md5": "864d98b3666c57ab0833d9915d210459"
        }
      ]
    }
  ]
}
