{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "9.0.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-9.0.0+1.21.11.jar",
          "url": "amber-common-9.0.0+1.21.11.jar",
          "size": 234124,
          "sha512": "75e2883999c2f025bf2cbfd7d61aa7167301e010fb70026798a8af1eeaadd48044debf244fbbe3aebcda234d11019630a1d96279832f98e2daae364da7314b8e",
          "sha256": "7d9caf63a23e26899ec54b2366aa82d1f69234e5ae8f7e476b1c63134fee2384",
          "sha1": "debf314fc9ef4c46db424f5ebf04b4e4f69e28e4",
          "md5": "f9f6c150f22c6a1f5f10e8ac2f78eb54"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-9.0.0+1.21.11.jar",
          "url": "amber-common-9.0.0+1.21.11.jar",
          "size": 234124,
          "sha512": "75e2883999c2f025bf2cbfd7d61aa7167301e010fb70026798a8af1eeaadd48044debf244fbbe3aebcda234d11019630a1d96279832f98e2daae364da7314b8e",
          "sha256": "7d9caf63a23e26899ec54b2366aa82d1f69234e5ae8f7e476b1c63134fee2384",
          "sha1": "debf314fc9ef4c46db424f5ebf04b4e4f69e28e4",
          "md5": "f9f6c150f22c6a1f5f10e8ac2f78eb54"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-9.0.0+1.21.11-sources.jar",
          "url": "amber-common-9.0.0+1.21.11-sources.jar",
          "size": 158381,
          "sha512": "fa4ff0b430f304c3577a1a8fdaebc8b8bad0c49d6c9c1f55d80348ca3321339c19753cf5783a3c6a21a1eb6ff818858ada7c86e1ee665176036e380637a5601e",
          "sha256": "78781fb435de0df3f564af5a060774383cc7369b1f6da4c8acf160ae570efe73",
          "sha1": "17ba0b6a637875c4fe3c68aa28847a20f2d87b86",
          "md5": "58e5e47cc7f6d846dbf94a0f7baad3e8"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-9.0.0+1.21.11-javadoc.jar",
          "url": "amber-common-9.0.0+1.21.11-javadoc.jar",
          "size": 627323,
          "sha512": "219553dac5e2f2433cec4c23da913685bc965f94771f85624704549d5790c888c6147cc0a25135af218bb05ed32cf1bdd13225243a9e4b5658a115a5fec92ecc",
          "sha256": "fd944926a4a3dbf6116c10c5e78a1eb14cf82f4869a611ec90ac871419f1bca1",
          "sha1": "9cc547b15ef8a84683cdf532808032093d5b60d5",
          "md5": "cc93ef40a0851310b725f083fcc30b6e"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-common",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    }
  ]
}
