{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "9.0.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-9.0.0+1.21.11.jar",
          "url": "amber-fabric-9.0.0+1.21.11.jar",
          "size": 281968,
          "sha512": "305e3f7add2e59b8a22f60fc22db109c560d1e27e59f455dafb19deb454248e7d4bab393e8b3e52fe13db9357412621e6b167be8d4f7bc702ca5f1508baff576",
          "sha256": "77be32f0c3c76e51ac958ce50125179465ace78986f395c0ed92825cefef6b5a",
          "sha1": "0822889e568340cf93174e0cbf5562c74524f856",
          "md5": "2811a127646681828414ab6cade3f84d"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-9.0.0+1.21.11.jar",
          "url": "amber-fabric-9.0.0+1.21.11.jar",
          "size": 281968,
          "sha512": "305e3f7add2e59b8a22f60fc22db109c560d1e27e59f455dafb19deb454248e7d4bab393e8b3e52fe13db9357412621e6b167be8d4f7bc702ca5f1508baff576",
          "sha256": "77be32f0c3c76e51ac958ce50125179465ace78986f395c0ed92825cefef6b5a",
          "sha1": "0822889e568340cf93174e0cbf5562c74524f856",
          "md5": "2811a127646681828414ab6cade3f84d"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-9.0.0+1.21.11-sources.jar",
          "url": "amber-fabric-9.0.0+1.21.11-sources.jar",
          "size": 181915,
          "sha512": "794cdce322b3a5988be48f2acf6b54bd44f6052a6e0980d053698fa84db1149ff75ea02e623e7ec511a787556d379d4f3d36ca15d3b064c6ba8822f9d789f5e1",
          "sha256": "31a8d9c7ee2033a5027c1568c14c8980e2fbd1b217588c8a431042e32c8d1c9b",
          "sha1": "ecb306762d4ca65b6206c755d02f1b3523be9482",
          "md5": "6507ccd17a14de81c53ec0eedfc7b993"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-9.0.0+1.21.11-javadoc.jar",
          "url": "amber-fabric-9.0.0+1.21.11-javadoc.jar",
          "size": 695524,
          "sha512": "0addd9020140fb668b0872905172cf1745eeb452ffa699126e2b4009303868c518771f11661810156ed18d83373b838473f8cb16cea0dd0ae5ee65c5620dfca5",
          "sha256": "502aede5754ea3beba7380041c68dcdda6aec41df2ea755033c0eef106796430",
          "sha1": "87e6d7d3f7ddde86805ce339cf2acf004031b20f",
          "md5": "ddb350f79ecc1b17f694ae059a1cb15f"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    }
  ]
}
