{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "3.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.1.jar",
          "url": "amber-fabric-3.0.0+1.21.1.jar",
          "size": 113611,
          "sha512": "227788c7eb9e542831eacfa4f8612fcb300ee88c47b8338973b9d58affcbbf771576c5d133fdb839f3ab84d950eb085316b50ba6bdb74ab4fefc4ff04cb8ba45",
          "sha256": "7df4a9e0e0ebc6ec848b0176d797d387ce6ab2516721e559f67259ccbb48583b",
          "sha1": "1773cfd74aa4b37d24c6627444400ca0591a24cd",
          "md5": "7b9da1846982033d243b57af23fa0c46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.1.jar",
          "url": "amber-fabric-3.0.0+1.21.1.jar",
          "size": 113611,
          "sha512": "227788c7eb9e542831eacfa4f8612fcb300ee88c47b8338973b9d58affcbbf771576c5d133fdb839f3ab84d950eb085316b50ba6bdb74ab4fefc4ff04cb8ba45",
          "sha256": "7df4a9e0e0ebc6ec848b0176d797d387ce6ab2516721e559f67259ccbb48583b",
          "sha1": "1773cfd74aa4b37d24c6627444400ca0591a24cd",
          "md5": "7b9da1846982033d243b57af23fa0c46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.1-sources.jar",
          "url": "amber-fabric-3.0.0+1.21.1-sources.jar",
          "size": 58246,
          "sha512": "984a7447d97ed485c0f2bc5ccf522db38ccd83a24581cd9c1b642ee85a0e7edc71940b0bba0a4b81fe1469e8aa1aa3edd8b78dc793e9e1a7d85abad3d4b57db0",
          "sha256": "5a814c4cb927f03a86f267b1f8a8f218027d8f05856e1f80072a3b8133656f86",
          "sha1": "89214ca40f065f235e4c8c02ce7890df5eb16e43",
          "md5": "ee8d5c6ce19cecc5812ddf673967bcde"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.1-dev-shadow.jar",
          "url": "amber-fabric-3.0.0+1.21.1-dev-shadow.jar",
          "size": 111541,
          "sha512": "1d471ac989cc451ea9fb9ea3cdcc6110944184d2b5721e74120ebe14e008128b8d3e0062ca0e8caf548dc9e347a79f1a9bd8b2a6341ebe9bec02e19a372196fa",
          "sha256": "1c7932c32f49d96a84fc9a212a304207310c38a9784444e58a135f8e977da8b5",
          "sha1": "777ad0a4befebf2ff789c559aae59d29a542064e",
          "md5": "7e52702c77635c466f71227789ce5536"
        }
      ]
    }
  ]
}
