{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common-1.20.1",
    "version": "1.3.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-1.20.1-1.3.0-beta.2.jar",
          "url": "amber-common-1.20.1-1.3.0-beta.2.jar",
          "size": 81347,
          "sha512": "433a8493b5805f87921e35b19993203dc066b45c91e6d25aae3f216f8e3c5e6190562e2e548dae3a8df7154c292895bbff9bbf77b9b627cb884fddf8547fbc6a",
          "sha256": "1b7af55459ba02ec2119892b38315591f986ca7fac924b00b457b87d64916064",
          "sha1": "879ffbcc2d8c94b4d51acf1c08e561033c6d188e",
          "md5": "850cbb5d69510029257c943211adc439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-1.20.1-1.3.0-beta.2.jar",
          "url": "amber-common-1.20.1-1.3.0-beta.2.jar",
          "size": 81347,
          "sha512": "433a8493b5805f87921e35b19993203dc066b45c91e6d25aae3f216f8e3c5e6190562e2e548dae3a8df7154c292895bbff9bbf77b9b627cb884fddf8547fbc6a",
          "sha256": "1b7af55459ba02ec2119892b38315591f986ca7fac924b00b457b87d64916064",
          "sha1": "879ffbcc2d8c94b4d51acf1c08e561033c6d188e",
          "md5": "850cbb5d69510029257c943211adc439"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-1.20.1-1.3.0-beta.2-sources.jar",
          "url": "amber-common-1.20.1-1.3.0-beta.2-sources.jar",
          "size": 69400,
          "sha512": "f9b2de6d0d344de7f4532caa2af0faad90c9f83df4e512add76c6a703c547b1a5229ae65ca2d357fba31565b13e7d23422b87213b521b4dfd58d24d1e803b491",
          "sha256": "3f6bd3d1b37168b8f721564c66120db22a3d4226339f01cc5c073970b4e38e8b",
          "sha1": "82dac2a00d5446a27c2e8f713beb131355ee95fa",
          "md5": "81e4d270e8472ccfb1a3d35aa4624b7c"
        }
      ]
    }
  ]
}
