{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "2.0.0-beta.4+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-fabric-2.0.0-beta.4+1.21.4.jar",
          "size": 84437,
          "sha512": "a35608a978b5298ff02a737cb1de26e371cb7f70b6e12b8db53f2074cef7b49f47da30f3d16e3118fd8d6dddf416c48f0576d10d97f106edc2083fd5fea2ffe0",
          "sha256": "baa8f1ba5f21a75aac9331ce2535b506e1043a813519cfafb684e643aa53e53a",
          "sha1": "dcc98fbcdd8ec92cbca686bd390aea12947e6b67",
          "md5": "48b62b93550ef5559791986e6d3e8939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.5+1.21.4"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "15.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-2.0.0-beta.4+1.21.4.jar",
          "url": "amber-fabric-2.0.0-beta.4+1.21.4.jar",
          "size": 84437,
          "sha512": "a35608a978b5298ff02a737cb1de26e371cb7f70b6e12b8db53f2074cef7b49f47da30f3d16e3118fd8d6dddf416c48f0576d10d97f106edc2083fd5fea2ffe0",
          "sha256": "baa8f1ba5f21a75aac9331ce2535b506e1043a813519cfafb684e643aa53e53a",
          "sha1": "dcc98fbcdd8ec92cbca686bd390aea12947e6b67",
          "md5": "48b62b93550ef5559791986e6d3e8939"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-2.0.0-beta.4+1.21.4-sources.jar",
          "url": "amber-fabric-2.0.0-beta.4+1.21.4-sources.jar",
          "size": 54402,
          "sha512": "5124c95ddada065445792c341580945a85db4e092fa359be0bfd5d5318e98e2aa4b591a030b39c0f71cd031390734fe4e442e52254847022a1d647cbb17e10ce",
          "sha256": "19b8ad8c34dac9f88c067f9c618329818f3053f8fe672f8981ddbd45715265ea",
          "sha1": "60213a677196f749c092991a5a8f99ee993625f0",
          "md5": "f5e2566b2dbfe1441bb54761669df6c8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "url": "amber-fabric-2.0.0-beta.4+1.21.4-dev-shadow.jar",
          "size": 83168,
          "sha512": "93ed1363ff9ce4eddaa51730e7ad33564a987793e719ecaed224f928efe73f642055777f461c6287d22f77edcfd61c20e4274a41bec920ea060449a92fcaa59e",
          "sha256": "b496ac54270e3c6557e02691496ae724a80e654b44a0ce4c3aa19dd42b1d12fb",
          "sha1": "bab788ef90a974554966bff2f1a27b5805d6709d",
          "md5": "f1b16b09762e2a702d840a2447f31e9c"
        }
      ]
    }
  ]
}
