{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10.jar",
          "url": "amber-fabric-8.3.0+1.21.10.jar",
          "size": 281210,
          "sha512": "42628f970f2d08e99bcf4ff1b7ab1273203d4366bb7e0281fa095693e973c887eca35478f20f32d9c9d469c4ae5b7f4d2c8b2528618f70b55f16d9758b3ddefb",
          "sha256": "f64e04f0f72c572542798311138ce216279d4e3f04f19c402b110819b313625a",
          "sha1": "0368f380370ab4732182e617bd9eb43bf00e20d9",
          "md5": "f5bbd09be6cbeb63a91a0d08312b3cd2"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10.jar",
          "url": "amber-fabric-8.3.0+1.21.10.jar",
          "size": 281210,
          "sha512": "42628f970f2d08e99bcf4ff1b7ab1273203d4366bb7e0281fa095693e973c887eca35478f20f32d9c9d469c4ae5b7f4d2c8b2528618f70b55f16d9758b3ddefb",
          "sha256": "f64e04f0f72c572542798311138ce216279d4e3f04f19c402b110819b313625a",
          "sha1": "0368f380370ab4732182e617bd9eb43bf00e20d9",
          "md5": "f5bbd09be6cbeb63a91a0d08312b3cd2"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10-sources.jar",
          "url": "amber-fabric-8.3.0+1.21.10-sources.jar",
          "size": 183252,
          "sha512": "1256493f52e708ed8bb76c2a4ac81b8bb4d8b78215edc5944594229e8ff1907e34dc1f5d6358254c2d5212ae2526ac3236bbac8631507845cdbdde476a0ac733",
          "sha256": "9fdbb7a106089b97fa7e9aebf477910879d7cd205f52989053eddad0872403fc",
          "sha1": "a8ea1c1c573a215fc5d62d17e4d6dc6a592dff4a",
          "md5": "d05c3872e77d51aab8eb24155fd7489e"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-fabric-8.3.0+1.21.10-javadoc.jar",
          "size": 693244,
          "sha512": "49b097e2abf92430423a76c48b95ed5c9b97638df5edf8ff9835e9e549c0359af0ad271724b84db75abdd980510db686b41a95686a55d035c1f0c4cb64c48bc7",
          "sha256": "1f623c1606cdefa160d538e9f32747a8462324767a7eec892c16c9d1496c5745",
          "sha1": "32f5c6f102ff978e0778d001006b3491c8b15d47",
          "md5": "053c66d141a553378af4a28bc462da91"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
