{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "8.3.0+1.21.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10.jar",
          "url": "amber-fabric-8.3.0+1.21.10.jar",
          "size": 282531,
          "sha512": "b0645b9faec90e368e1502d80b843d97482a86bc136705a81c2d4530ca94610b6c15b9e53d9796a2a657e9333c532d346c543fcce9303794612b0eb0d448f09f",
          "sha256": "4baa9f0e209bfd1efbd3e14b0e8c9842a5334edd349a832e5a71ecd9ec7196ff",
          "sha1": "8ab434625a148e3e196260d291b5b9988a4587db",
          "md5": "ac76c448e7bb594dedf94db4dbec537a"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10.jar",
          "url": "amber-fabric-8.3.0+1.21.10.jar",
          "size": 282531,
          "sha512": "b0645b9faec90e368e1502d80b843d97482a86bc136705a81c2d4530ca94610b6c15b9e53d9796a2a657e9333c532d346c543fcce9303794612b0eb0d448f09f",
          "sha256": "4baa9f0e209bfd1efbd3e14b0e8c9842a5334edd349a832e5a71ecd9ec7196ff",
          "sha1": "8ab434625a148e3e196260d291b5b9988a4587db",
          "md5": "ac76c448e7bb594dedf94db4dbec537a"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10-sources.jar",
          "url": "amber-fabric-8.3.0+1.21.10-sources.jar",
          "size": 184475,
          "sha512": "72cfe5c970ba75936a24cb5704f558ffbbe1ce08cec390e131254a94b7b2df13ac04df34be1189b2f118f47764dd708d82309aa9fff0947217ff34765ce90b87",
          "sha256": "0387aef1b88377ee1a1cb9cfff051dc059754286608dc4c60c6abc3fa6d1ab2c",
          "sha1": "b18378ea14ea3ca87e3204285c5086e239019054",
          "md5": "26906224ef175fecd93f353c0e127a50"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-8.3.0+1.21.10-javadoc.jar",
          "url": "amber-fabric-8.3.0+1.21.10-javadoc.jar",
          "size": 695371,
          "sha512": "579fcfb099c06a3b5f3185017f78c06e8babd99df64eeeeff025c618a83672a524d9cf3fb872b69d8c63ddbc1886c5eaf90afc6aceb022ce893424ef7d32b94f",
          "sha256": "355e18aeda736116493f8fcbf66f30b5079faaba57e49b4d73d412c80e25d3c4",
          "sha1": "6a85516f5199d054644957f486320d73b77f99e2",
          "md5": "22b9b481b6873537883a486f89bc5bb3"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "fabric",
          "version": "8.3.0+1.21.10"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-fabric-1.21.10",
          "version": "8.3.0+1.21.10"
        }
      ]
    }
  ]
}
