{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "1.2.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-1.2.0-beta.3.jar",
          "url": "amber-common-1.2.0-beta.3.jar",
          "size": 84699,
          "sha512": "f225b08531e47fa5735ceaa88da7d0542b40879398da64635d1abca27bebd572f4d16e0b552cf1df6214d5c8b79359e6bfe261ef4d43e10cc57dc62a6f789c82",
          "sha256": "8bf6219b25f77d7adc71c134632d3a85d5dabff61efa757f768cf6498d78e501",
          "sha1": "dd0e33c16e5de2093b140584ff66399f70df62b7",
          "md5": "50d7143fe3d23b22d4864b3d2ca9df7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-1.2.0-beta.3.jar",
          "url": "amber-common-1.2.0-beta.3.jar",
          "size": 84699,
          "sha512": "f225b08531e47fa5735ceaa88da7d0542b40879398da64635d1abca27bebd572f4d16e0b552cf1df6214d5c8b79359e6bfe261ef4d43e10cc57dc62a6f789c82",
          "sha256": "8bf6219b25f77d7adc71c134632d3a85d5dabff61efa757f768cf6498d78e501",
          "sha1": "dd0e33c16e5de2093b140584ff66399f70df62b7",
          "md5": "50d7143fe3d23b22d4864b3d2ca9df7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-1.2.0-beta.3-sources.jar",
          "url": "amber-common-1.2.0-beta.3-sources.jar",
          "size": 71064,
          "sha512": "af9bc01f92f069dbc92619c8895be6611c1b831ecc59178de88729f5469a4c5a6bf398f4ea0fdf5dfa9f4eb5b2f96462e903b1155bf0e36426425cad16a0dcab",
          "sha256": "150d127d9bba53d46401f8a4429d680c1b9763261d567efd26e56799cde90a54",
          "sha1": "d89da5c6187a1e1a15d3ffb97a230efbc76bfc8c",
          "md5": "0d3d7208c21d229586c647ca6f43043a"
        }
      ]
    }
  ]
}
