{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.template",
    "module": "template-common",
    "version": "21.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "template-common-21.1.0.jar",
          "url": "template-common-21.1.0.jar",
          "size": 4290,
          "sha512": "816ea159f3f8cb633b7f7da0fcbe949b9e74efe2a56a2d0a770afcebfbb52e3f2d7421aeda54aa2e843139c82fe6dbefa67c3d73f3415ca5d6b47e47ad014359",
          "sha256": "44e6cc4b9ea371f1cabf9ab1daf9ef3961cf8db2ac96ec3ef61a0946007c93f3",
          "sha1": "8a908ed935acd6cb15a3f7d8f019febe82e94bb1",
          "md5": "7acca723f341c7b6154c4c3a82c3458e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "template-common-21.1.0.jar",
          "url": "template-common-21.1.0.jar",
          "size": 4290,
          "sha512": "816ea159f3f8cb633b7f7da0fcbe949b9e74efe2a56a2d0a770afcebfbb52e3f2d7421aeda54aa2e843139c82fe6dbefa67c3d73f3415ca5d6b47e47ad014359",
          "sha256": "44e6cc4b9ea371f1cabf9ab1daf9ef3961cf8db2ac96ec3ef61a0946007c93f3",
          "sha1": "8a908ed935acd6cb15a3f7d8f019febe82e94bb1",
          "md5": "7acca723f341c7b6154c4c3a82c3458e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "template-common-21.1.0-sources.jar",
          "url": "template-common-21.1.0-sources.jar",
          "size": 2759,
          "sha512": "4fdd3b8487af1d7d52d4e19ec0e381181676b998f2330df9d5fe28574d10265f3d0f12c9d122e2a79afb30e36321f14e0ff4194cece9f5a33b5ea5f96cf29eae",
          "sha256": "9696b8574a4873886ce89f6421fd6458c1cc0b0139fed1fef412e6e00b821688",
          "sha1": "32eb3eb135a224ba2588a1ff1ea383165a955305",
          "md5": "7698568b23371ac7dd6724f1d75782bd"
        }
      ]
    }
  ]
}
