{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "1.3.0-beta.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.21.1.jar",
          "size": 85224,
          "sha512": "8e10f7bffad6c79c4aea062ffcc1c0ad50078d879cf8eeedefa7dcc010b66b78c9b815551c15371cf8f45a0245f40074e7c04795a14560fa923b6a2a9434977b",
          "sha256": "3499240442da7801b01b7cc8544dff086349135fa08a646401843dbe9073bae0",
          "sha1": "385bdecf8abf81b8102423f25269ccb6301e511c",
          "md5": "a48c4191774fdb8a0c5a96c284634d93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.107.0+1.21.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.21.1.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.21.1.jar",
          "size": 85224,
          "sha512": "8e10f7bffad6c79c4aea062ffcc1c0ad50078d879cf8eeedefa7dcc010b66b78c9b815551c15371cf8f45a0245f40074e7c04795a14560fa923b6a2a9434977b",
          "sha256": "3499240442da7801b01b7cc8544dff086349135fa08a646401843dbe9073bae0",
          "sha1": "385bdecf8abf81b8102423f25269ccb6301e511c",
          "md5": "a48c4191774fdb8a0c5a96c284634d93"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.21.1-sources.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.21.1-sources.jar",
          "size": 54406,
          "sha512": "0ec5a57ee48e1ee33d8ff931555aebb4d5c43ab62c833e920c46d13ede343854f9d427912defd654ae51f029d68f4f60f9b71a937f75c245d3d91fe60b429be2",
          "sha256": "3176ece24ab0a95ef7687b5d78ca7ce930337339a1f0920d9e5e528e6923a19b",
          "sha1": "f3d9b09307bfb3bf9968cf160d544c9a6d47f080",
          "md5": "1718ee40409ae69726b515bfc85936e4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "url": "amber-fabric-1.3.0-beta.2+1.21.1-dev-shadow.jar",
          "size": 83979,
          "sha512": "907ebe317156ac49b3dbcfa57db4aac1527f4290bb4307e147b85447d8d5b6cc23aca39b6d3b7407ef258ae7eafe75011829db8f42cc2a2bfec981cc300c218a",
          "sha256": "06e0857e07354de592f3d9af29dd38fe46998c00603b6d020919082c8400fb93",
          "sha1": "882827ab64f0740a37c772208d4dfdc465864591",
          "md5": "a593f0e5d747954c8d552551afbc2ba5"
        }
      ]
    }
  ]
}
