{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "9.0.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-9.0.0+1.21.11.jar",
          "url": "amber-neoforge-9.0.0+1.21.11.jar",
          "size": 277573,
          "sha512": "014c518edbb2cf4275f6f25e5dd2d3e7f2a18198a2b2407bc51540e93420bf76caca578654d0c39c610fe46d53ee2712bf3c259841000783e1fd5660a79f8807",
          "sha256": "72c790a2198ba98784c7b07ffe53169ec5d3f98ed678fa1462ca81dd50068939",
          "sha1": "accab24d9933f8b1c63f8d31d404cde27848221c",
          "md5": "41a3c4f80af5337fdc9e380d437a3d90"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-9.0.0+1.21.11.jar",
          "url": "amber-neoforge-9.0.0+1.21.11.jar",
          "size": 277573,
          "sha512": "014c518edbb2cf4275f6f25e5dd2d3e7f2a18198a2b2407bc51540e93420bf76caca578654d0c39c610fe46d53ee2712bf3c259841000783e1fd5660a79f8807",
          "sha256": "72c790a2198ba98784c7b07ffe53169ec5d3f98ed678fa1462ca81dd50068939",
          "sha1": "accab24d9933f8b1c63f8d31d404cde27848221c",
          "md5": "41a3c4f80af5337fdc9e380d437a3d90"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-9.0.0+1.21.11-sources.jar",
          "url": "amber-neoforge-9.0.0+1.21.11-sources.jar",
          "size": 176876,
          "sha512": "b348c8dafa4ecaa5be0cd9535813a03a69920fe8a66b95b6941c94cca67bb9dcc64c2a6f4414f43e17be7ac0c2871dd782171352fab2a7a28e9fcfe0ded16a0a",
          "sha256": "4bd48f23428f056cf3e1c56b42ea893c899d758e64acdd3e779534d9cf39464e",
          "sha1": "479e1595957ee81e2e6c5642c68bbb92bfd7cba1",
          "md5": "0adba3383c638ec6eb9b95be99becaf3"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-9.0.0+1.21.11-javadoc.jar",
          "url": "amber-neoforge-9.0.0+1.21.11-javadoc.jar",
          "size": 695383,
          "sha512": "420e72c6f19449ba723493c19fb224f484867d65afa96c180a3ee353cefb477e893c4d981a4fe0c917a4f320ac97925e62b0557224a99c37ce35cb04fa8efb86",
          "sha256": "3497cf6d7306765098e1b5f3ac44967b2388be0798203897da50b039c88b3ef1",
          "sha1": "5e3bec3ddcf1c6bbb7ca223cddd4507bd5f084e4",
          "md5": "93690dbcd172b5e8086977440e3199cf"
        }
      ],
      "capabilities": [
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge-1.21.11",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber-neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "neoforge",
          "version": "9.0.0+1.21.11"
        },
        {
          "group": "com.iamkaf.amber",
          "name": "amber",
          "version": "9.0.0+1.21.11"
        }
      ]
    }
  ]
}
