{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "1.1.0-alpha.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.6.jar",
          "url": "amber-fabric-1.1.0-alpha.6.jar",
          "size": 82309,
          "sha512": "32a6c8cddb145798400c76bf46b1f30613c5bfe6056e87537bd416c13ca232b3550b7c4fc95204c5b02f439efd657cfa01c0265d43a0fb2b9149bd5ae8afabd8",
          "sha256": "9f5e8197977779c257243b8f307025e408b619df3c001f80f93c15dc90fa1902",
          "sha1": "37aa914c22cdd5229660232216023a2ad228db69",
          "md5": "f4728bddde29496ca59ae16d05d6324a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.105.0+1.21.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.6.jar",
          "url": "amber-fabric-1.1.0-alpha.6.jar",
          "size": 82309,
          "sha512": "32a6c8cddb145798400c76bf46b1f30613c5bfe6056e87537bd416c13ca232b3550b7c4fc95204c5b02f439efd657cfa01c0265d43a0fb2b9149bd5ae8afabd8",
          "sha256": "9f5e8197977779c257243b8f307025e408b619df3c001f80f93c15dc90fa1902",
          "sha1": "37aa914c22cdd5229660232216023a2ad228db69",
          "md5": "f4728bddde29496ca59ae16d05d6324a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.6-sources.jar",
          "url": "amber-fabric-1.1.0-alpha.6-sources.jar",
          "size": 55316,
          "sha512": "2a94551c7b9fd69b8bb0036d8273ed8b5df6f050bb79a69334ddb5280599679f21345775ae20fa0f3f878bc05fe670d7c9da13a25dfe2fa92baee4397ee2629e",
          "sha256": "cd1910c14c140e1b18caa244585b1da431cc6292baf3ebc035953986ebc452c9",
          "sha1": "fe29bd8cd301a1d55cb37adefda956c344d5f82b",
          "md5": "4ada8d8755811b0670267f3f06980821"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.6-dev-shadow.jar",
          "url": "amber-fabric-1.1.0-alpha.6-dev-shadow.jar",
          "size": 81213,
          "sha512": "3d4e5e1614e25a38f3c8e8f20f36aa33a4d01cdc83d00aa78d81a741e926a6754178f99257c54ecd1285c785b59e80ccfdd1470687fe65ccb09b9693fc03494d",
          "sha256": "ce0c800102e04aaa6414ba090f5534cb20d42d12b89496702a62b7cb3a23a566",
          "sha1": "e6d672860d242879223c15831537dcd3be8f05ef",
          "md5": "3b380fc570f2b7ec1edeb944269500af"
        }
      ]
    }
  ]
}
