{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "1.0.0-alpha.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-1.0.0-alpha.1.jar",
          "url": "amber-common-1.0.0-alpha.1.jar",
          "size": 14896,
          "sha512": "b4433c0e26c4001a966a5b49320615ded473d388031bcff2f2e6b94fc541eeed2aa1aa5020aaf4bb85a0344feb31dab0d67741c1b9d1c683ae7a6206d8c82fa2",
          "sha256": "a9cb62c4ace383b93842045e6901ac7a03a09e357de0de190af6cd534f59e3a7",
          "sha1": "8716682cbde3da9f67515f29a7e9502d174fb981",
          "md5": "57b2c087e0ebd8ffec349fbb584805b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-1.0.0-alpha.1.jar",
          "url": "amber-common-1.0.0-alpha.1.jar",
          "size": 14896,
          "sha512": "b4433c0e26c4001a966a5b49320615ded473d388031bcff2f2e6b94fc541eeed2aa1aa5020aaf4bb85a0344feb31dab0d67741c1b9d1c683ae7a6206d8c82fa2",
          "sha256": "a9cb62c4ace383b93842045e6901ac7a03a09e357de0de190af6cd534f59e3a7",
          "sha1": "8716682cbde3da9f67515f29a7e9502d174fb981",
          "md5": "57b2c087e0ebd8ffec349fbb584805b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-1.0.0-alpha.1-sources.jar",
          "url": "amber-common-1.0.0-alpha.1-sources.jar",
          "size": 8224,
          "sha512": "236a7a848a47be066eec29593806e1bd55b252f710ba700db619b81e6f50a204955ac03e741c15eab0c3902a39ed95f908c1792dd11216199b9a8d35d7718bec",
          "sha256": "936f3d5fae9d40553f656e3872d1affcee1fc59d12cb27385232e8935efd65af",
          "sha1": "4f6aa9a08fc65a67179615e964c5ad5243079e23",
          "md5": "fd2a5ee857bff24dfd297605d2778763"
        }
      ]
    }
  ]
}
