{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-forge",
    "version": "1.3.0-beta.2+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-forge-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-forge-1.3.0-beta.2+1.20.1.jar",
          "size": 81977,
          "sha512": "30d0c38831110b9ea5dcd4b3db6370f6011d5669a35ca09a802f90cbbcb2ce5bc5dbce130ca28e8bf9286df967a7f9f55e56adff3691e5bf89a2ccc2ff90b3ec",
          "sha256": "04e849b48b1e4278aaf923af6cfb6ffc1a30424fc47f63bd998da74a27ba15a0",
          "sha1": "634411bb649b04ccd723eb855bf83890c4ca64a9",
          "md5": "554893d6c0f890ad4daad963e6c73749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "9.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "amber-forge-1.3.0-beta.2+1.20.1.jar",
          "url": "amber-forge-1.3.0-beta.2+1.20.1.jar",
          "size": 81977,
          "sha512": "30d0c38831110b9ea5dcd4b3db6370f6011d5669a35ca09a802f90cbbcb2ce5bc5dbce130ca28e8bf9286df967a7f9f55e56adff3691e5bf89a2ccc2ff90b3ec",
          "sha256": "04e849b48b1e4278aaf923af6cfb6ffc1a30424fc47f63bd998da74a27ba15a0",
          "sha1": "634411bb649b04ccd723eb855bf83890c4ca64a9",
          "md5": "554893d6c0f890ad4daad963e6c73749"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-forge-1.3.0-beta.2+1.20.1-sources.jar",
          "url": "amber-forge-1.3.0-beta.2+1.20.1-sources.jar",
          "size": 2898,
          "sha512": "d5f87eb28ed0d2d4e3fe4fde0080e7af29d74024d6c727e1b9d0815f9e7fd3e07c619fe1c0768164d9bcece90bf25844428df66061c6ee27a9f22e9424d4206c",
          "sha256": "5b33cefe43ab9d5b238ad823635ad94afb39fb1177ec98bbfa87ab28bcfb6903",
          "sha1": "98afe261658a71ae6f7fa27b7d1ff55e216e2cc4",
          "md5": "9c3c1968305dd2e3758f06a798580790"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-forge-1.3.0-beta.2+1.20.1-dev-shadow.jar",
          "url": "amber-forge-1.3.0-beta.2+1.20.1-dev-shadow.jar",
          "size": 80476,
          "sha512": "a855350de9f5e78eca17953b1ebba98f79e234980bb7edeeecfbaafa879e937abff99fd39049e62e5c6d07a87e085d3006d62ed2a6b4cee653146996d8a31564",
          "sha256": "02797c3a27c7d5942d819d70d3e6f19f884e68dc027689dc44f21a8e5ecccbd4",
          "sha1": "189e12c5ac1710eb00958b427b541229adcd2813",
          "md5": "d11db9d00216dd3d7cb94c4ba23ef462"
        }
      ]
    }
  ]
}
