{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4.jar",
          "url": "amber-fabric-3.0.0+1.21.4.jar",
          "size": 113380,
          "sha512": "f99255dcf8c3f94b059557c494eb3fb0af91506adc5f52bd3fe6f70a928a6be3cffbccdd483b731715d67fefcb844bb5336321ca2d1426858bb5c553ec61408e",
          "sha256": "e446873974dd4c9e2ac7ae400d48f576a961d339f2d326e1be83ac6925669d43",
          "sha1": "44201d45d0393c0efbf0a06ab744404799670aca",
          "md5": "513357fd10379af1a616b8a6ccbd4f59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.5+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4.jar",
          "url": "amber-fabric-3.0.0+1.21.4.jar",
          "size": 113380,
          "sha512": "f99255dcf8c3f94b059557c494eb3fb0af91506adc5f52bd3fe6f70a928a6be3cffbccdd483b731715d67fefcb844bb5336321ca2d1426858bb5c553ec61408e",
          "sha256": "e446873974dd4c9e2ac7ae400d48f576a961d339f2d326e1be83ac6925669d43",
          "sha1": "44201d45d0393c0efbf0a06ab744404799670aca",
          "md5": "513357fd10379af1a616b8a6ccbd4f59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4-sources.jar",
          "url": "amber-fabric-3.0.0+1.21.4-sources.jar",
          "size": 58240,
          "sha512": "46008af405baf24833fc7e38e5447d5af86605ccd61090a9c1745ac9145bae35de386edeca8fe94517b27306c407880ccaf0a5428b76e19cc3ab855183075a10",
          "sha256": "99ebc2c2d5a8343bd021c7c8d5608bb6d34ca187f3b1420b7d4fa5fb34d686f8",
          "sha1": "f2aa937a3fee2f14334bb7e80ecef60fcef1a808",
          "md5": "e5400d62329824d7ae48b094adfce2ca"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4-dev-shadow.jar",
          "url": "amber-fabric-3.0.0+1.21.4-dev-shadow.jar",
          "size": 111250,
          "sha512": "a1d901d5723d3a0296e71b1a2ba2be25ef2390d53f3b401223dd9985a357a9b119540b8187df34bbef2c3d944a18be6355b9701bb188b4872981cd860ddf9eb9",
          "sha256": "950f42e944763d3a8550667d056f6f9eaa72cfebc793db1f9571f512cd553da8",
          "sha1": "b90126b738bedf0115e409597e341a81d6a007c0",
          "md5": "be3e8e649c350c250197a046e982c080"
        }
      ]
    }
  ]
}
