{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4.jar",
          "url": "amber-fabric-3.0.0+1.21.4.jar",
          "size": 111695,
          "sha512": "0e66c467efab779651d709c402358840e0879cc77e4749ecce9867814aa3bf266bed026c85f51e487b3ebeb3f0f38c24b7a7d04b72c6838eb8bf5265e70efd17",
          "sha256": "c7b902a55e57ee2565b92d3ec1091c23088b1a20edfdbdccd410b657e09e0666",
          "sha1": "24b527a7dbd28dfed3698973340aafd81ecc1e09",
          "md5": "f5733692aaaef0057277b5d12ab42307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.110.5+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4.jar",
          "url": "amber-fabric-3.0.0+1.21.4.jar",
          "size": 111695,
          "sha512": "0e66c467efab779651d709c402358840e0879cc77e4749ecce9867814aa3bf266bed026c85f51e487b3ebeb3f0f38c24b7a7d04b72c6838eb8bf5265e70efd17",
          "sha256": "c7b902a55e57ee2565b92d3ec1091c23088b1a20edfdbdccd410b657e09e0666",
          "sha1": "24b527a7dbd28dfed3698973340aafd81ecc1e09",
          "md5": "f5733692aaaef0057277b5d12ab42307"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4-sources.jar",
          "url": "amber-fabric-3.0.0+1.21.4-sources.jar",
          "size": 56994,
          "sha512": "a7dfe9f4e59703ea4b45167e3635597348f45796ef622737cd0b60e54063c111422c7e15c8ccdc62b625c8398937f42ceeb3fe60fa373b70e289f7c4e198cb9f",
          "sha256": "6ca0efe127763f7a98677ba881b7e24e27a2b78ba612f11b3e981e00623c4485",
          "sha1": "3973c22c9101875b454d1747ca66d510ec0b2101",
          "md5": "33dfeca43b34c2b16e3867c6cb4edcf2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-3.0.0+1.21.4-dev-shadow.jar",
          "url": "amber-fabric-3.0.0+1.21.4-dev-shadow.jar",
          "size": 109648,
          "sha512": "e119472a3b933f1233c5750a4d0da4902c4d2a3e035910af0b8b92864d402ec8f517abe2cc0033b01ad09355bbd1b52c8fea48b34b014e7ca740b274204b899a",
          "sha256": "6329da432536e3f4b46497794103354e7703097fac688c1733a2371f1775f21b",
          "sha1": "88f9f82e15372d23eede5ea9f4ee2fc7268f879b",
          "md5": "9e199e9f54e1484d279cdc1d41c20aef"
        }
      ]
    }
  ]
}
