{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 111801,
          "sha512": "27c9016c0e9f1de64d241a04437128e223d5de5671cc53f3bb25711f2f70d55efc1d69b3a2e6196b2d891020ade790ead92c3321f38c4b2da96925a9f898bac7",
          "sha256": "b51ad3cfc6e9cde67cf36720f4f80a713ee72aa2975a0d58753c2d24220c64bd",
          "sha1": "34647a1a4388329f2ac1c1a0655b25744add594b",
          "md5": "e8ad574ede95c945218b4bd92ab9936d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 111801,
          "sha512": "27c9016c0e9f1de64d241a04437128e223d5de5671cc53f3bb25711f2f70d55efc1d69b3a2e6196b2d891020ade790ead92c3321f38c4b2da96925a9f898bac7",
          "sha256": "b51ad3cfc6e9cde67cf36720f4f80a713ee72aa2975a0d58753c2d24220c64bd",
          "sha1": "34647a1a4388329f2ac1c1a0655b25744add594b",
          "md5": "e8ad574ede95c945218b4bd92ab9936d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "size": 56663,
          "sha512": "1c48d5efb5761b069dd8b82e14aefb090f16c17eb42c23eb9ce535057e9d8242321667fbd323f222f6ce685fdf0f80197b232751b5d720e43dda9a7a31a46691",
          "sha256": "23ad9bde753f9f2b991ee960870e40b42f77cd5c70aca125304c6d9c97be49a4",
          "sha1": "1bf465efc00d20ec81cf24bbe9aa4bc355848bdd",
          "md5": "00a62b9ee09da8d36de6841f64ba93f2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "size": 109572,
          "sha512": "44b2a55bbe624fcb11fcdb33e58cb1f97d0174e8fedd894222cefeb3b36b1a49734183e77f592fb0bf73a32b011c15c578472cedc89dfe9fb4f17e4ed1877107",
          "sha256": "30e362e7a1d44a8d14f1fe22109a0576e80d06bcfd67ee0089e15e0e06d3d31f",
          "sha1": "a070917a42f78e80d6f1fc161e884fc2f440bc1a",
          "md5": "eb12ced6ae40a09ece4857826f26fe78"
        }
      ]
    }
  ]
}
