{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 103548,
          "sha512": "6f85e1ca9210a00d544f65beb47014bc7a70ce1f62d04fa851ea89cd1a306a5d9602cda5a2b26116774e8facfafd739a08f083c82f6ab36d74897b71ec7383a7",
          "sha256": "250f7383d6f47d1a19c8e70c2ae6db191026bb7057161b4b1ec79bc5b85cf607",
          "sha1": "26ea39a0c52210de68682a127f8d5a9727145228",
          "md5": "ec91fabd867e88977720960151a8753b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 103548,
          "sha512": "6f85e1ca9210a00d544f65beb47014bc7a70ce1f62d04fa851ea89cd1a306a5d9602cda5a2b26116774e8facfafd739a08f083c82f6ab36d74897b71ec7383a7",
          "sha256": "250f7383d6f47d1a19c8e70c2ae6db191026bb7057161b4b1ec79bc5b85cf607",
          "sha1": "26ea39a0c52210de68682a127f8d5a9727145228",
          "md5": "ec91fabd867e88977720960151a8753b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "size": 55499,
          "sha512": "c149a0c28eaf443fa8de26889b621ffd313d264262aa32d3310b21548346d13fd02fe292203cc5c66c81361c774b7a3815af59fcee543caa080a64910add21f2",
          "sha256": "ee85689fcd13dc4552f849e63a84fe5b2a5f67b03d0bfc3c555a0eb0debc7c4e",
          "sha1": "7671affdb40d561631bbe6189af55bd668921bf6",
          "md5": "b4674219f63c1bd882d95e633c8139ad"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "size": 101615,
          "sha512": "b66d9678f9b7c301e4d62858690deb263e86526c706bb8672df35fd36bfcfefffa24ffd708b459108a292955ba2f69d82b5bf2c3484fe59f998bb31cc10942f7",
          "sha256": "bcb87bae7ddfa990f7d5da21190543642f9b15f9958a5d72e8a33a1b0c08b20e",
          "sha1": "0e43007d22d28d34aef56612c759204740ad589f",
          "md5": "48e00b1268d056961ef2d9f84741c4a3"
        }
      ]
    }
  ]
}
