{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-neoforge",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 113027,
          "sha512": "4fd0d2ba374b05011054c2ea00b06f1ec1beb7e41696225e5dc2e70e8fb8b4402d715532945687f6c81fb2f182d1bb3baa8f3ca7c984466e02d90481f800971d",
          "sha256": "ae671870ee3e4a656d3a3201484eafc5f3dd6d7a6097ccade8bc34d9b50821c6",
          "sha1": "d4f9d7d69bb82ba7649b3180289af9fa5f1c6c9f",
          "md5": "64379ccf9796251e2f6dad3ded54bfbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4.jar",
          "url": "amber-neoforge-3.0.0+1.21.4.jar",
          "size": 113027,
          "sha512": "4fd0d2ba374b05011054c2ea00b06f1ec1beb7e41696225e5dc2e70e8fb8b4402d715532945687f6c81fb2f182d1bb3baa8f3ca7c984466e02d90481f800971d",
          "sha256": "ae671870ee3e4a656d3a3201484eafc5f3dd6d7a6097ccade8bc34d9b50821c6",
          "sha1": "d4f9d7d69bb82ba7649b3180289af9fa5f1c6c9f",
          "md5": "64379ccf9796251e2f6dad3ded54bfbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-sources.jar",
          "size": 57882,
          "sha512": "ae40e91d29715966b16ec2cd6b39cb29400ce3c0d12cf879296d8004e412dca7c481f5f0ae30ef26e6be95881e4351c13304c50faed6ec1561e605b3cd3b6c28",
          "sha256": "e1eea481720d80cd1567364e2030bede7ed3e20d1e3acfd8147dddc308ef980d",
          "sha1": "0109996b2fecb39f9de13ac0a0587fc15ec83601",
          "md5": "563cb03b3bfe77221b9e12ed5a8e28b2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "url": "amber-neoforge-3.0.0+1.21.4-dev-shadow.jar",
          "size": 110715,
          "sha512": "892fd5ebd89da7aa78beafd6ff32bd3e43cf91e467e6b6d3b0924990529b25087793926efe8ebe358a04a48c6a25bccbad5d58bd7a275cb9169d50e9a63638bb",
          "sha256": "3406cbafe740b80dffae24a814956206a5e2cf57e36443c2445cb993c921125d",
          "sha1": "aae7a3816d428df37300d5c11b448fdb7ffb1452",
          "md5": "1a8f2bfc2c341970805791e1a501cc7f"
        }
      ]
    }
  ]
}
