{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "4.0.0+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-4.0.0+1.21.5.jar",
          "url": "amber-common-4.0.0+1.21.5.jar",
          "size": 107865,
          "sha512": "f5cffbdd30365c3b64b12b0eefe0cfb73b9205723fde91717f5d532f0170b93e872eba7937aecd12c20f3eee65b4dcfdc825f53bf2588c5be4a11e4110614ee7",
          "sha256": "115ff14b1164ac1eefffd7a64fedcefee77e4510009ca21976d82c0cfc77f95b",
          "sha1": "c5dcf9d407dc2d08d41d8795db440855549b22b1",
          "md5": "f7fcaa8b24aff9f01c1dc231943e6891"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-4.0.0+1.21.5.jar",
          "url": "amber-common-4.0.0+1.21.5.jar",
          "size": 107865,
          "sha512": "f5cffbdd30365c3b64b12b0eefe0cfb73b9205723fde91717f5d532f0170b93e872eba7937aecd12c20f3eee65b4dcfdc825f53bf2588c5be4a11e4110614ee7",
          "sha256": "115ff14b1164ac1eefffd7a64fedcefee77e4510009ca21976d82c0cfc77f95b",
          "sha1": "c5dcf9d407dc2d08d41d8795db440855549b22b1",
          "md5": "f7fcaa8b24aff9f01c1dc231943e6891"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-4.0.0+1.21.5-sources.jar",
          "url": "amber-common-4.0.0+1.21.5-sources.jar",
          "size": 86825,
          "sha512": "0933f3c5bbb4e5f1952cf8483a9a2579e37c923a93a349811487661dfbed2b46ae8025b882a0571b32862d6c2ef24348f0185140e8a6be0358a204005eecb6f5",
          "sha256": "283663892fcfb111bc49e03570cc2ca90741da2d46adcafe7cc04f4011eae8db",
          "sha1": "4cbcb08283e98dd11c9e89923a73d8996bdf5ada",
          "md5": "44f40064a75280bce8fa19dea4207b1a"
        }
      ]
    }
  ]
}
