{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-fabric",
    "version": "1.1.0-alpha.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.7.jar",
          "url": "amber-fabric-1.1.0-alpha.7.jar",
          "size": 82312,
          "sha512": "ea883d7a1ccb1885d350ea18cffa2f13ed4262db8759073a7bb11af38bc41ede68a9357d6cc941e786ab8499fb9fa6e03581b60b2372fa31de0f812a8efd2ef3",
          "sha256": "814f2d3e10892514ae03a5cfbaadb03612844e8ce5f9a9172e3ff53fa5a20478",
          "sha1": "fadd573f1ac37a7f345400f5f8f4b5f8feab6a1e",
          "md5": "94aae239ba47a6d2cae1defc99d080e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.105.0+1.21.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.7.jar",
          "url": "amber-fabric-1.1.0-alpha.7.jar",
          "size": 82312,
          "sha512": "ea883d7a1ccb1885d350ea18cffa2f13ed4262db8759073a7bb11af38bc41ede68a9357d6cc941e786ab8499fb9fa6e03581b60b2372fa31de0f812a8efd2ef3",
          "sha256": "814f2d3e10892514ae03a5cfbaadb03612844e8ce5f9a9172e3ff53fa5a20478",
          "sha1": "fadd573f1ac37a7f345400f5f8f4b5f8feab6a1e",
          "md5": "94aae239ba47a6d2cae1defc99d080e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.7-sources.jar",
          "url": "amber-fabric-1.1.0-alpha.7-sources.jar",
          "size": 55316,
          "sha512": "7288269fdd59554f9632b8d3fbe74b388cd3f395cc455c11772b5e25a4304e49d55ad1429c9622d399f0e7a6f6e9ccc9f03a18d82447eb1962536df6a62ef841",
          "sha256": "858533283f6e0f2b5d4bea1371da6f65f5417e1828d0927292cbda52ee8f7df9",
          "sha1": "3e0dee1b1b40070579309d972b835b56a534ef47",
          "md5": "3c432cc95687df21c5cd3501e585ffd8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-fabric-1.1.0-alpha.7-dev-shadow.jar",
          "url": "amber-fabric-1.1.0-alpha.7-dev-shadow.jar",
          "size": 81213,
          "sha512": "6294b85ed37e06413a2c3fb2df56ba6d8337bc2fa948dd836774c58c338a474eeeb659fff2c90301e33d03178d7991645e84a09243a30874d69a1cc2c7f30f78",
          "sha256": "1a2534e91a6c0e3b3e46cee823b42b5ca1073431f4c042fcb9b6c7d1113b6b5c",
          "sha1": "8e967978fba05f4a8f95d853d8055f3a023cc8b2",
          "md5": "57949a198b1375dbefb554be834e54c2"
        }
      ]
    }
  ]
}
