{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4.jar",
          "url": "amber-common-3.0.0+1.21.4.jar",
          "size": 107866,
          "sha512": "a3facf904e2ceec00be514daffffc22434fc77c0577c6bbc43aee65150dca0847dc7ff8bf2026c8d2021f93ee243ce2d3c5169cfed9846658bc5850869597d82",
          "sha256": "c3e3209e62a816cb3634cca0e9bd5871f40d6b7be09cc9c431aba6064c0b4628",
          "sha1": "e5abaebc041b45ce89f891d022eb17ad1b979236",
          "md5": "2edb2f53a10a03d359cbded3cac0984b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4.jar",
          "url": "amber-common-3.0.0+1.21.4.jar",
          "size": 107866,
          "sha512": "a3facf904e2ceec00be514daffffc22434fc77c0577c6bbc43aee65150dca0847dc7ff8bf2026c8d2021f93ee243ce2d3c5169cfed9846658bc5850869597d82",
          "sha256": "c3e3209e62a816cb3634cca0e9bd5871f40d6b7be09cc9c431aba6064c0b4628",
          "sha1": "e5abaebc041b45ce89f891d022eb17ad1b979236",
          "md5": "2edb2f53a10a03d359cbded3cac0984b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4-sources.jar",
          "url": "amber-common-3.0.0+1.21.4-sources.jar",
          "size": 86822,
          "sha512": "53feb88313cb8d6936fff07aaa63a4475e5feb1c1bbefde24aea3db05fba261e68e9cbf74c9ba0b65c2fbb9cd907011d2b3f27934a67728450f5567ca9e69990",
          "sha256": "f85b23082d0eb76e775082c6fda32484c07934876f3e8d221ef729f78a3abc65",
          "sha1": "1a90f09989431c6140b8db7844ee66062822b298",
          "md5": "a2227f87f2de87428461ce367ac63f30"
        }
      ]
    }
  ]
}
