{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iamkaf.amber",
    "module": "amber-common",
    "version": "3.0.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4.jar",
          "url": "amber-common-3.0.0+1.21.4.jar",
          "size": 107866,
          "sha512": "cc157be5cded59835ab11111e05fb449b5c0224001ebb02c11fe407e8332f243d865c2c83f472f7e659f5ceeeaa9f0269d57ed28a9145a75cd2fc35e6d741f9a",
          "sha256": "02bcca30fbed95c451efddffdb4be47c4e95fa9ceb1c6a9752f420f376c43aa8",
          "sha1": "4d878abdf44e21a1e6014536a28f55ecb2359575",
          "md5": "6d5f81dd54f3a0ce6fe3bdcd2c91e3ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        }
      ],
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4.jar",
          "url": "amber-common-3.0.0+1.21.4.jar",
          "size": 107866,
          "sha512": "cc157be5cded59835ab11111e05fb449b5c0224001ebb02c11fe407e8332f243d865c2c83f472f7e659f5ceeeaa9f0269d57ed28a9145a75cd2fc35e6d741f9a",
          "sha256": "02bcca30fbed95c451efddffdb4be47c4e95fa9ceb1c6a9752f420f376c43aa8",
          "sha1": "4d878abdf44e21a1e6014536a28f55ecb2359575",
          "md5": "6d5f81dd54f3a0ce6fe3bdcd2c91e3ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amber-common-3.0.0+1.21.4-sources.jar",
          "url": "amber-common-3.0.0+1.21.4-sources.jar",
          "size": 86801,
          "sha512": "a1005213f05f7618051e294eb50cf492c1979fdad75294e6b67bf414ff9a97fe39d62caf185684c23cba7df3a803f479ec489ac95949fb9ef0c3a0276ca0a1b2",
          "sha256": "a5698ba1e3c10b4ea8d18d033ca7cf766a007387b301751cf969875611361453",
          "sha1": "b7a0c219d55c186540ef977605bd86a844ab2804",
          "md5": "c224d3daf45e81d38f1f079028df4639"
        }
      ]
    }
  ]
}
